{{ $global := . }}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress
spec:
  secretName: ingress
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.deployments }}
    - flink-{{ .zone }}.{{ $global.Values.domain }}
    {{- end }}
    - superset.{{ .Values.domain }}
    - argocd.{{ .Values.domain }}
