{{ $global := . }}
{{- range .Values.deployments }}
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: {{ $global.Values.namespace }}
  name: {{ include "flink.fullname" $global }}-{{ .zone }}
  labels:
    {{- include "flink.labels" $global | nindent 4 }}
spec:
  image: "{{ $global.Values.image.repository }}:{{ $global.Values.image.tag | default $global.Chart.AppVersion }}"
  flinkVersion: {{ $global.Values.image.flinkVersion }}
  imagePullPolicy: {{ $global.Values.image.pullPolicy }}
  flinkConfiguration:
    {{- with $global.Values.flinkConfiguration }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  serviceAccount: flink
  podTemplate:
    spec:
      tolerations:
      {{- with $global.Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - key: "zone"
          operator: Equal
          value: {{ .zone }}
          effect: NoSchedule
      containers:
        - name: flink-main-container
          env:
            - name: CLICKHOUSE_PORT_SSL
              value: "8443"
            - name: CLICKHOUSE_PORT
              value: "8123"
            - name: KAFKA_PORT_SSL
              value: "9091"
            - name: KAFKA_PORT
              value: "9092"
          envFrom:
            {{- range $resourceName, $vars := $global.Values.secrets.FLINK }}
            - secretRef:
                name: flink-{{ lower $resourceName }}
            {{- end }}
  jobManager:
    resource:
      memory: "{{ $global.Values.defaultJobManager.memory }}"
      cpu: {{ $global.Values.defaultJobManager.cpu }}
  taskManager:
    resource:
      memory: "{{ $global.Values.defaultTaskManager.memory }}"
      cpu: {{ $global.Values.defaultTaskManager.cpu }}

---
{{- end }}
