{{ $global := . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flink.fullname" $global }}-ru-central1-a-rest
                port:
                  number: 8081
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                port:
                  number: {{ .Values.superset.service.port }}
                name: {{ include "flink.fullname" $global }}-superset
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                port:
                  number: 80
                name: "common-argocd-server"
