{{ $global := . }}

{{- if .Values.ingress.domain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
spec:
  {{ if .Values.ingress.use_tls && .Values.certManager.issuer.email }}
  tls:
    - hosts:
      {{- range .Values.deployments }}
      - flink-{{ .zone }}.{{ $global.Values.domain }}
      {{- end }}
      - superset.{{ .Values.domain }}
      - argocd.{{ .Values.domain }}
      secretName: tls-cert
  {{- end }}
  rules:
    {{- range .Values.deployments }}
    - host: flink-{{ .zone }}.{{ $global.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flink.fullname" $global }}-{{ .zone }}-rest
                port:
                  number: 8081
    {{- end }}
    - host: superset.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                port:
                  number: {{ .Values.superset.service.port }}
                name: {{ include "flink.fullname" $global }}-superset
    - host: argocd.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                port:
                  number: 80
                name: {{ .Values.ingress.argocdServiceName }}

{{- end }}
