{{ $global := . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
spec:
  tls:
    - hosts:
      {{- range .Values.deployments }}
        - flink-{{ .zone }}.{{ $global.Values.domain }}
      {{- end }}
        - superset.{{ .Values.domain }}
        - argocd.{{ .Values.domain }}
      secretName: cert-manager-cluster-issuer-private-key
  rules:
    {{- range .Values.deployments }}
    - host: flink-{{ .zone }}.{{ $global.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flink.fullname" $global }}-{{ .zone }}-rest
                port:
                  number: 8081
    {{- end }}
    - host: superset.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                port:
                  number: {{ .Values.superset.service.port }}
                name: {{ include "flink.fullname" $global }}-superset
    - host: argocd.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                port:
                  number: 80
                name: "common-argocd-server"
