{{- range $componentName, $componentSecrets := .Values.secrets }}
{{- range $resourceName, $vars := $componentSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ lower $componentName }}-{{ lower $resourceName }}
  labels:
    component: {{ $componentName }}
spec:
  encryptedData:
    {{- range $varName, $value := $vars }}
      {{- $resourceName | nindent 6 }}__{{ $varName }}: {{ $value }}
    {{- end }}

---
{{- end }}
{{- end }}
