deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: NodePort
  kubernetes.rest-service.exposed.node-port-address-type: ExternalIP
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgBpf9L7mk0b0dOYRuY2tDUHpA0pRjIybPYLyItGKZkuwo/9sirhb7tCV3h+fy1fjtYxSYPpiTuX0Z8mJCYZqgLXmWjA9HYVfKPUI87oQPOMQMQ7AOYsdv4cObg01rATIJQI034PAkqMwf8YGxTMbMTl2fKtNJU6EmMVdDSZwOl6VDri70ejaT+WCywDKI4JRDMRG3uo3XBFaF2laWwWPgh3i51zLDOhKTaAXhHgfbDmpgIpC4Ey23Yqm1y0LNhmIH/7hLN5MVEGCqQMQU628in6RHRHA7Ti8Z01qQ0uxLbHAAwkzULxYoiEJknBqAkaDwXCnqcvz0hqH7mDxBZloUeNEYuYbcK+fFs7Ohag/DCO4NIuLdyR1/BKTpo6J4+9IEXLHdFRreI/xFzVeFZtN2A3yDS8TkgXxDgmxWskOVHbTL2vdKGxORQI3AjBKo3955g6wIa6DY11Pa1mrzsJmEx1R6VKfGVAsPj3Zf9yyXSmFQqfsvk12t9AKiNdBCcisk2qGV4kWdSshAkhdtz3qqXpNhua4Av7Wg8l71Cn+v8cF3EjwlNNPsfrfTSE3VlpA3H2kotUuru0Wh0X3GMZPOwmMZokzNiHm8clbjnWDd0FFth5lSjKmetPWkLQLIzGOEtr0XwR8xwRrzR+1Y/92/2khSlwg/hkvL59MrOkAPrno+LFRv2qjPTXHa4oeyV/BUWq9ZNZKw==
    CLICKHOUSE:
      PASSWORD: AgBFKsfk67Ct72iocQewG5G5hjZUe124xK37FFRQF3GCw5dCuJNfrzro9wjNH3adGGbKsnVRXS43Jfiaxn6GLwuO2r1J13CXGbqN0xEv2vY97hHrMnxsVvZamGjhg2SFeWuNLkY7AZoawXj+qHKTV7M8UBYbJRPmXXHzerOFy6iOlUGB9EFubrPM+UJ8C1SkYbNQK2qu12lqzlwW5fZkvBVX9ffJVK8mj+QRBzsshbOvrGMAbpb6NpTmVzNzzoi5nAVrolYZXUsJsmSOTxoUOEEVQwKrBK1rhAz+z9ipUkmOuRBooqQFXVYOloX+meBoqS5R2Z/2eJjMy2xyxPMq+drqbsTdGCKNrbCwAZGIw/sLLCFzvee2gexTsLd5w9k8yzCwaa5D5Dj1czyMI15XpPII2EYn5FMEmZvIXCkZ7sg4PSt6HY43B7JEeVO8NaUW0MeRBmTvmyb8aLVV4KZCJoFlXlGHjD2dhMO7tz/72vVJHQgoMBAK+jH8g1+a69IqTzJOefu67vKVVB7zumi7JIjc07t8FjkxOKyqHIRjn9qUZmZdgvOGgMJL177qKQ6XgMgFTE7FYWEu018fe7ZWWcTucQCFFRnrxdU3ZCWa4s0gPUvdsHO/gM0eQlwxtwp+4JcvQsfrVWZCwmr1w7OtUhUypyet50cRgZ9KkZQrV0Rz8Pzc3jJYfac8HvkPJwB2B1d17ay05g==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgAIWBSlSHKqW9wcy+Z7Xo29U/JJJ3X5oiHDVFdAWWsKImGZeC3ZkKxCR28MhoV3EDDhlY0fpi4ScQtGRN9veD3HIal7132tqsD7Wss7CTvJ05vsDvxdsfyl3dAvLsOYXEFz63HfhTIIJSz+kUPD1Uz9L56b73W9yJarsKLpEYY2b16FaPiKvwFrnB46nemSWZwP61ftTinntTs2MopALgJvsK8KBmnXikyXDaxcyFSmGpubDH+P52cxvJzyMVJz2G6R8TUyFZWjXVqgNFnSuvPAqKMkBH7vy8bzktdo5O/xI4WhTpsZP2XVCcQPmfbDqcgA6W9MDs7ctBpyL2njPkFpz3Z2Yv5Fe4ly3SuxagqCpYSQo5GH5SI73FpKte0uVBmKOYPE/YbHaHulwNSsDKCV8EQ4s0bwzJjvLKSS271V0zP3xcxsydeBwqpDML/4f6NXVVxtClbvOV8gwKqhMkp1Zfzab2hxdlWR65dYIAziASA9s6Fjh22ZzCRdnQTSKOEh1rPpo9xslEfYk1KTfY5+NILNTZMBTjqU+xlOVnMtX2UiG912Dw6j1L8B/fOXzyIfrafvyViDexvVf6aJCmz6kTtBEpWQVN95WUvj50LjNR6yNQ4BRhd9j0ihX5IIOpSx2DzlMX0oB3uvDCQFm1G5CrEh9fXA1032uw30E0IbNBTnw9sGS0HDBKIc/keDyjdQBQqlCg==
    POSTGRES:
      PASSWORD: AgA1ejCQskKjT8i86r3Gw+bslohdJMVN5Ui8VKkDA8wyOJcW7js7Hm+BF7WR4kzsHQKvNc0bitPy7MQSXf5f+GRVyiNfKVp6/QaW7BRajMA5CMW/kbOqXKHWanGWnCX5Ic0zEeqdB2/hJJYENypVx9rYk/EG17mhewaLx5DCINT29+9q0RvimHjo2kL1VCcWiB405s0/H+pFN/yei4uFkbxFdorHJ9OQ6dyHB9Wo50XYDpp3a5yYweqVy/zJAiSzshYuqLcTVgrQpQpnuOL9QQXBh/DfFpzclKsJSleB9HFwcRyWtc6HHHRgOw6eKApVzKlZ3AEj4uW1qXsV7FckX/bhtoe+yagrp8X2KujCMltOH5Ndu2nfi4P21kzEapGFgPhR4kp1qetIc9crWKjnDK6EB2Q/C8AvumrOYx6JVo3ljT6rSeuJ/koOXRvYbFN1msPsKAv6+Ze+5NLqxWlojo26XcZF8Nsdvf0+a627OBjUIeyszXpA0GDmWM3Nhlv2Z4srDIz2yXvqXezCHEK+qL+/DzmizJYrkWki/lCO7yPFDksNLQRgOk3AWGR9+cHln6XFVD1r0Rs2qu3RezIVE7is6OBN5peXriI3IB7NDmNIiL4Tq+es4WV4nLLTKFyAZSXClpeA6dbyZM9B485I3igmivJcIFVGpIKgrsJQ52jMv9tjE+2XJU1B6uLjz2kbuvRR67kSdw==
      POSTGRES__PASSWORD: AgAclkPvEQLnpGIKf0Ls8Q1zS+SWRi8vvoZhPis9hyrQv1S754FuVefttulpi0p28VJVUXU0FUt7wggdSbbYYRAhZtCoRaYGjApeEFe+H4qhQux2MUhpszO1IFMLoGqlmCf/BL51BiSryQFqfWfZkvzhymUw0Q4rFtBPmPCJCcjQHDpa662SWhFvpOmStU14DsFNWRN6et9fZhHzHaVYA51ES63jpbXYDGAIewKxgCwWkgkxKoMoEdF0WR/U8ZvkkCZ9zLs6bMlp7siii88+NiQgKtQFEwHMDkB0BPFmKeCDaLAqkHwaegQa1dY5Na4QEcryiNTS87yAmRPAQt+RNpGA944iqgJhRHqRGPxUm9s48VVxTCqSY16vOyDM05d+fLMj/HzpGeWehXj6dNGHdLHbFsRIF6TUuFFctLPR49XiFTfUAl4hYhBtjizxrWFeqCu3E3T9liwnwpkhifU/8JInt4Az3CIBaQc4AFUQJG4GwljenvDyPTbvmzZa0cJRXJhfuqoFaZentVdgBNiDvMOS0iiT5eG1Uq35Da48wpX0ES/XqTt7XctAXjcd+FVn+u6JDfxNn8g3sJqaFL4/Wnr5ntqe/ekl/3SkE7dSm4FjEb4kWgMk5p8GpcV4R2sK7wvW27mV2BtWlYvG87cxkGwQW6j3WNSD4iQKS3j8yJDSsxzyhRQNsbk7E/joHgP7FWGDEJbVsA==

superset:
  service:
    type: NodePort
    port: 8088
    annotations: {}
    loadBalancerIP: null
    nodePort:
      http: 31000
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: false

argo-cd:
  global:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly

cert-manager:
  tolerations:
    - operator: Exists
  crds:
    enabled: true
