deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: NodePort
  kubernetes.rest-service.exposed.node-port-address-type: ExternalIP
  job.autoscaler.enabled: "true"

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgC7d88wL/oK+77RUmZFfSG2gBTEVrUVLN5I5X1nqR5ELOB1s5rEKRdh+YFVDoXVB0kud6vN3mP4Gw+iFBPGIv9VdNTsMNe7SEKVWXhXD/Rk3ScZxEyPVsoTn1dSH37YkkrB9mt7rcwO3/I47HqbhBbXkqLb7WMchJ2Yi+D0CBdOdKJQQq1KAK+QSYcJ6empHYlce8iZ+aTS8QHGw/CYf2ucYp1Bd/hKAHhEsu4KJ8hKJ9Ot08z2InpnDwFmk7ORIxU9/hrU0k4C1dtQigziDpmOIjtEbAeJS3nZEX3z20RjF6Nd+sbV+nvbEwCZ8eCiGEBbI/ag7xwAhDqcVS93/EdF4y3L7Xu5LzsO1OVUlYen8qZuqNaBxYbtqQ/mgoLyPwYbol5Um4+92QWQrA5zhTalezv6lTDWi9Azgr78i/lEmQRrhLieDxWQrNEezIApOlq5C5ASWWTp2jrvi1x6y2MvYoLzp8u5DPVFN45kS9zIZ0cksh2ibONJXmofQSwSwGKYc0iJzCMh0ppboyPTzk1uONMhm0VqP30sxH1S16r4B0Gsk68OGXDQzbB9TwrCTOtNGS7rURvy1YiLdiej0naNerROOwleg8/DZAkQ1EYVtsXh4GQxnDW1vg3z5oXWUnqC2N3pb3j0x9Qiyrwv+JbiHvHfdPmIx+KqRrfqNnpQ2JFd2TEnKQpq+k1N+reeRRSeyV5Jdg==
    CLICKHOUSE:
      PASSWORD: AgBNapW5obcr1s7vrXuflEucK+45uTloES/sQSdRhlmM7CFz0uLshnP2GNGh01hQNZNUowZHAcUbUuMtx4WrI5tVIGKC+/+j0Lg9qnTUlAi7LSSJWhAK96cjLujw4thvLk4NdwL4fJYOggrrlRN7/bED52an8o8LTF11sQXndA9d4XeqlleAf+jWBDp3R4S6XdVU3c3ahNy60m4Jksj9YnBJJ0UiK7y0YNoAQB5IAizCBpj8Sl9q0MWZP8KJb+GtjMT6yp87zqiYYWvWIeUqbfxV9IfjZJ2ilG8PrLK4meG604za8KJH7eb94l+pqiavknjdnfrutgbSLgWBuyJQItZl+pSry44oa+Mku2EqIJRgjVrX24lmaWKy643wY5pnwC3VTf2min2jAGmrOKOIGWpMgHTrKPrcG6onUHUJ1CiIgBBrzmGE4hnvtrapGlkqdwb+pYYnwYNXG6GwwkCmhrVC+EMXmYiPQj2I1Wml2CbmGMDY1/4i+wSKhKoyCPk9YaSqSo00RQiTfLDbMVXRFCUSGHNeJ+pYb3aaUWlKjgUVCZ3dthyUOhM6d5FnnXLtKDR8fdjTxV6ExlwrxrJWo4l4BFrmyv8rbfurqYfnN0DNJ170oD5MaHsfvIETkU4CtLQmILihuAAzCm3Q41kHo9ac5zIM2N0prrzIK7EhguP/00s91Mnney5NK2k8bHDbW/QxHLDMHQ==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgC05KonbkyF0lBuPIILy6tRTWoCjQgZ06MfIw/eNyXkYlHwcjD7PawASWb4eH+6uu21EPGt4O5zZhxN1BrUDkmaSZcMkGHKrf4SzUf1kYB8b98AG1cUWGnu7wDQxm64Z4vUamf4Rg/1WNOXewcR9R69ogQ+aWmcYyqp5T+6kE6bzZ2E/FqnIX8OPUAdausXU6F4UcbKPc68YMzKCRa+MwqLE5x+AlWLNoCXMmjlZr5pUmjzAMF6VwS/3sIfGlob+fxxC3uWjJENh7gGDzWMbUY3TsEiPdC7XbXw9usmqBKUj6PqVxzjfY18OndvBuk8Z956jISjSkqMwuEFdzgTrwlfVApW2cA5qt2EcbWI0j3Pt4cnbcBR8wMTDqfJ1dEi27dswhdivnza3yzGLCx4n4ukmjSGlu0a6odPx9+JY33/B34GZgRl1lICIZFe7Ky+beJGhaYe0wULA/1skPE2Oli7UU4rvx/9Orkr16R7fwRVPQYSSiAh8XxLzPv54qDvSgbQuesouDrRra+3f66NO9KOJ7QdKnTpnLTMmBT4hVoTqAwxXOOOYyBZUToLT/C0pco2iWoQp5VkDcwoqxgrH3APT03+4L2loDPk2b1p1SLUYM97Un/uTLfMiv6cSG6sp6htArba4CY7qmxz+coRQ13c4WaipRlaUhvx2+BnQ3dNtKdi5nfsnfTXO1EBES72qFt/VWaPmQ==
    POSTGRES:
      PASSWORD: AgAZlehdABkEBKUxqnPrTIJ+NcK9OKESvrzVGep3xyqjlGeMAMsYSoM00Wfba4B92XPtXos5/nti2IHSPFoKtcFn1WQE6RdH4IRNnBa8tai2Srvfimp+MEX4NppNdH1yG2y1UPqUSiO5aJBvpf28cReCdHDM0wJps4lvcFOzKeOe+mGMXLiGT9QosnFdsn7hX7kqVMs9QwgmPWjVBICCfl8Ef9odv7IhkI4A3Xye+ilFP65hLiv4bbtnIuWVyXtdVmLrYHV0jJjnZO6musCugeE3xOhxYwTyD7sXqGw1fmb0C5OsEMCH1qQ1kp6GCiz8Nr5BTkdHzIDL+urFmyrrGXdya+erZdCdLg6vEg8yHHGbQzgZHaIoctom8Z7xFX6ZGpnTDGyXIkPgv1UQeHmsYYmKIm4ZyPugS1rzk1VEeebKGLI3P7+L9DXHIR0WamvkrC26F9NCt0VBCkq+XgWnwIRS91zSiiHcJd2DN97Wzs2qtdI5yur9s4PY5QGbuxGrah7HuucQP7p2aF+o49ltHhMyDZCxE1YLO1MRjs+jZNCmI6MX+6uBj41j1czNCp9lcmLcM97nCaL4gMv1uCD8COs6ppx5EroFZ9nlavrg1Fv2+7dFyo/TceqXVVFKF44VGMhuWmskzHeLwYpWiZrrSPhZ67Huqbu8gLoeIQ1CPBgmTNHzu/NRJtpEhMkp7DTO0kkuDUqBqQ==
      POSTGRES__PASSWORD: AgBz8gn+GQsUtcnFVs/3tqEhFLWYv4svkn/ePz3UFFdqDvCBnLrAUUMNUfStMxUTUPaBrRiUbdlIchcROT1e6QTFo/CvAgZe83q/wxupdgFmzMW1QbEkOduBDUB8StqZC3gr1XkYKDTtpeQ/tL1cYP+obmJopJBjowIiyLu819rHqTg3YyEi2PdDTBXYD5vf1t0r8L/jj1hqYp9zvE2AjYxo+h4/w2VY6V2DtoFHE69TIT88yJHfHBRSmm15nvTpsOjzrvqpSMHFzWAGy1kAub0yMbHSqHo66oSMeMpwCZ/cv0PwIVKKx2FlbRNSMSYs9Fzy/ImFNhjOJwYABou4aPkFEe2j3L+dqLhpgzOT+WLckiabiydQCcg4fTIywTRLqlSuWpQat8G+kuuIkchF2WFNPfkjtdE/sRhbXjwLHAvNTW9iB8CxWqV13U/IqK82gUijtJd1ilkpXXVLmOm+o8gSqYWjxz+GuqSRA74VGdCFaZWeKYr+g19lAqBp7700fq2Z7W6bt/WAcGmthlQW0O9SBuwPq0m5LXrLD5rah+xupZ1PuCA0N4t4hPYBTeOG2JLK/uQHgUAA2mUm9+Ureb+DYV9gaNCVj0lY4dMzooolRvh+vtRHhFXW3TEPfheZPx+7cBtbPPULId+HnfXASin1f9bAlr7bA+OoTfoRF3uX3z/4HmPTwX9KV9CrIlhU3WFT2tmVYA==

superset:
#  configFromSecret: superset-config
#  envFromSecret: superset-env
  service:
    type: NodePort
    port: 8088
    annotations: {}
    loadBalancerIP: null
    nodePort:
      http: 31000
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
#      existingSecret: superset-postgres
#      secretKeys:
#        adminPasswordKey: POSTGRES__PASSWORD
#        userPasswordKey: PASSWORD
#        replicationPasswordKey: REPLICATION__PASSWORD
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth:
#      existingSecret: &redisCommonSecretName superset-redis
#      existingSecretPasswordKey: REDIS__PASSWORD
    master:
#      extraEnvVarsSecret: *redisCommonSecretName
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
#      extraEnvVarsSecret: *redisCommonSecretName
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: false

argo-cd:
  global:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly

cert-manager:
  tolerations:
    - operator: Exists
  crds:
    enabled: true
