apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink
spec:
  project: default
  source:
    repoURL: https://github.com/mm-kpfu/game-data-platform.git  # note: the oci:// syntax is not included.
    path: deploy/flink
    helm:
      valuesObject:
        argo-cd:
          enabled: false
  destination:
    name: "in-cluster"
    namespace: default
