apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gdp-flink
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - '*'
