apiVersion: v2
name: gdp-preinstall
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 7.1.3
  - name: sealed-secrets
    repository: https://bitnami-labs.github.io/sealed-secrets
    version: 2.15.4
  - name: cert-manager
    condition: cert-manager.enabled
    version: v1.14.5
    repository: https://charts.jetstack.io
  - name: ingress-nginx
    version: 4.10.1
    repository: https://kubernetes.github.io/ingress-nginx
