# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
argo-cd:
  fullnameOverride: argocd
  global:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
  configs:
    params:
      server.insecure: true  # for common ingress tls

# https://github.com/cert-manager/cert-manager
cert-manager:
  fullnameOverride: cert-manager
  nameOverride: cert-manager
  enabled: true
  tolerations:
    - operator: Exists
      key: CriticalAddonsOnly
  webhook:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
  cainjector:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
  startupapicheck:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
  installCRDs: true
  namespace: cert-manager

# https://github.com/bitnami-labs/sealed-secrets
sealed-secrets:
  fullnameOverride: sealed-secrets-controller
  namespace: kube-system
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

# https://github.com/kubernetes/ingress-nginx
ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    service:
      loadBalancerIP: "158.160.134.182"
    ingressClassResource:
      default: true
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
    admissionWebhooks:
      patch:
        tolerations:
          - operator: Exists
            key: CriticalAddonsOnly
