apiVersion: v2
name: gdp
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 7.1.3
  - name: argocd-apps
    repository: https://argoproj.github.io/argo-helm
    version: 2.0.0
  - name: sealed-secrets
    repository: https://bitnami-labs.github.io/sealed-secrets
    version: 2.15.4
