argo-cd:
  global:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly

cert-manager:
  enabled: true
  tolerations:
    - operator: Exists
  crds:
    enabled: true

sealed-secrets:
  fullnameOverride: sealed-secrets-controller
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
