argo-cd:
  global:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly

cert-manager:
  fullnameOverride: cert-manager
  nameOverride: cert-manager
  enabled: true
  tolerations:
    - operator: Exists
      key: CriticalAddonsOnly
  webhook:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
  cainjector:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
  startupapicheck:
    tolerations:
      - operator: Exists
        key: CriticalAddonsOnly
  installCRDs: true
  namespace: cert-manager

sealed-secrets:
  fullnameOverride: sealed-secrets-controller
  namespace: kube-system
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

