deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgCT8sGI3x/wUKJ3rGGOxgFpfjJbogWXfEEofYuWNFpBmXBjtQf211jEAuNiukKawNJ7x8TF+SymV/BIkoQQnrq6epzM1hZZKHlBwAmhx1069tjXxyeRKX5F+TBYl4MU+Q2oMniMWfi9nyFlFoI5PV6/XpRouVF1C8xdCOq5mTm3Ht7vXkZ/8tt/BvlNuf5B0mcnblRCINg3asOzwOWfBmJDlKpKF+L2Nwa/JtdS4tA0/tqLdwd36rskV7agx77Tr6v5FHmUFkgIzxke2eEuTSGtQHw0jhHfPvj3DHXNjyiJkvNaM8BBaQLt3LrelpHxivFEFF4n8yMrcY9x26DYUrwbApo5DuaTw61yOwDoj9PIIPY8+aQaCHJUEllfKTVnq/m2VRAhdB/rWWs2Mxi5dU3mOfbWi5qH1AO+2JX7DrCecZjyJzXjO9ljdvIJUwPdILBQkAIlKRI5RxZiMROAx1dChyj+mZUNlM2NJtYWQMHvw/nITLTDp5tW75Od71onEs76M9McLytRphLGDkzTGMDv6PAHAatdwgwwXIl9vTt0UZxOSgM89dl9QvW9M1GT5GsoFnV0jS+h7GGTfkSejE+cUNAhPdXhjC860cA6LZgZXHubQlZBHvji3Yn8Dul3m7Xun9F2WTdrCqkAbeKh3hdwuG/TOLBIT5Vb0qjUPYvlejbg9pCeoqLWn3PrtgIfAFJILGpcpg==
    CLICKHOUSE:
      PASSWORD: AgDEejEK/jFA1omDD3wgHyE7cdYHwvDTSAY6QqQstZrtvsxyHeWuCimaH1XC6ou/YPUsOfmXjUHg2fn/oWl942DGKLlcG3LoFpkCpHwMXoXDqESHCPqcr/vKWreY0Ico1C3FH18BUkNA4bdcQyi+npY6x/xqYuG33raHVyumAnNBV0hCuX/we810Ih3Eo6qb38k1wbs3Zj5eE8KkTo6KFYrJqnRFV3ZHjWDhQzb8EmLTaul//dUbW2wBHBttQF+AyLQIqoMHJ2SoFSY1G6G/lhZJ0lXz4QehKb+iuffKwC+vhvOSy6w/c2TWfZNFB1+QoDoEWJy6YvzoIMGrY+dIBwFObDY6osMlfeN4IOO5PQvRgjDxht+t1Bu3Mz1TsfiaJBEcsDsnLcrQlSsJn9TkeyUVQv4YaITAjX75KoypI5L2qlvTDafEIiFdTvA6yRJcsNh2YjLX+f6ovA4dVFisVkuaRiIVG1qqiSDgHWDgPrAoJAz3oKjcc28QnRNu1Vcc1PaZCtjDayIcTapjaOb4fWUE0fmL1Lphrr8qqzplW49iYCLZiBUuxLmubs1HqMWQE2dbn6JKkECetXR6Bjk/TqkKze7BhF2Kk6iafsUHTM2h6Rkx04I+OXH51dxpWu8oW1axT1mjLzFWKDMySz2rLSv6k+zH/x3YK3OXmAfEv/pmucatRzkfuErrb9IfX8l36MMFXqfMpA==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgAfdYhrsjSjC2Ox5IN+U8NdWfXte+vEZx0djKM02TWQrb2kxW/SlN3k7lUHSptRWfd85ksntd1b/e3BPwnAEpk5d6tB3OMX4kYnaZDtOPvzXyFMXVeSjPC+PT21eN1uoPgFFJ+aTACgfZMkrgECQJqP8P9DdwAk7wUgda1e4tBZR/d6drS3IXLdYbb9+DNAGOwCXbthGAQzQvOiFWPYINSyKsNFWEeSTwahC6BrL9P0ghbfkyVI0ZD8C0MBhXpPd+o6wvIFQ++GAGpzyeVpJZAnVThLV7VfJDcCZf23RK0ahlUVke19AV3ZrYY4wiTq495D3PypaUs4x/PpM6V89+akvDHY1smIT+SXgP9HbRkYcpcPaSit8ffpfsQcMWbaDpPokfu+7Xe18F0RjkKiIB1tM/HdlTQ8rIb1LvsipYcv1D6Zx0es4FvDqvUPA3IObBrzbRrc4pM2QjTP+AF0k8WDeN7d5Jf7szTnVlDzBEKF5IGre92QNhkNTyy3fmLhBSIWoPbY3T5gcWKR8hemlbb9E0DmLNkM/l59xnRNxBuDKyvw5DvxM6953lkdACbvpeACKoZZNYA2j3taPqmed+UVZNdUEy9u6kScRxJyCoDdZQSQpui0nmGesAwpWuiVAfR9RcDP8bJle234jLGboHCleV0D+eiYhytu2Ivlouv/z87pZgllS23wLYMo8DXqojFsbkc2CA==
    POSTGRES:
      PASSWORD: AgASykbcYAoAYlQOkyXW4ygcxeeR4a9RPl08cx3Zr8TJVzDrP3kvenIVwHJe9/Hvz5GA2wl20vhLmD4o8ghT6q9Aae0DM4zd+Wmz803eteUv2MtAuMRcG5+MvgqRCqeiYADYlmtmP3rKOoZ9o8fnon9N1LF1yuWPZEQ0cvSXSTuWOcSFqJRh43FKpk2uJUpmwhgjKSkZFK+gaiiCyHOAV4NOru6M4QaQ/65NCnqs0LJnqfU6iZ7/V8ZnFuz65XUqCyuQk1dXNqGBS7XO52avul645zjXIQXSAll3Q8l2zcMAIFoBAS4jhv4hWuM+Te4FvMoOTonf6JM+HLfpg4TNNGxGJ3ZCRA6FffnGiez/lcO7s1itfYFD8ufCQkZo6AlFKPX176KeIOEWFu0JTAbftgRhVREOWD0tIo6KFfS8UNBkf5sU3Vqu6J1jEOh7NP0BDoI+79tMafCAFwq/NFao0866fAPpwSaAInu2elO5y7mgt4Oy4d8nkIUNB88PJedgwlu9BWTZH5lADWZeu4xggLw6+Gcacx2CT7mVsgmbV2wb6JL5B7cKjYsN25Kv4hBWUpijZ24yDKdCHtWeLo/Hw5LEHmiFuFqs+g/dRHEk35+qeoc4SNwU5/mlwwzq4ZNCQP+IMbv0lVmz52/09nsMiUo1LKRacfNFJO72x1mURlyeBpO74StwK8WIO5nr2PKIVjvaFNjvXg==
      POSTGRES__PASSWORD: AgCQrFOkG6cWBFsRrrZINwbKy/dBmwS1Bm54fWFjpgPiXipo+90q86qVo4t+yzTiIeanBLL/eoqajIy1pofZIgTQUZzvqlq9qJb5U3A4Cre10Fqv16Gq27sE9uxfSvtkKlUJz7iZ9CTlsuYZA5+KeuqUD7sIxtt7xrqzbjm1N9j620ModxLFiV8k1LsqRcbbiBv/xgPiZP1GwAsfqWOXe7ElAgODIu94quv6Tumb7GHRsYriqfJIy4yAUIMIKczw6ZYJ2c1NqQX3Ge+UY4PR5dXJsAVv0uFUwhrjHCURRlZPWoPzQS6LdlRDcBZzj0ARyEnu9d1HAXitoQo061d7ElKuNwsJ8yAoEMDTuIB7jYbivFDRD6qKFc6vTPX7gGx+5WZ5CeJEpM4VxzJn3tmwZ2ofIuvvOOpZ7Aqxew5O3bKeWM/mjUfFdfeq6rSpbSYY1OfSVnFAGVlCgCFIwVhjgXpAdz8XEyPrRA460uXbqHhHHDsdO07KY59sqzjnx5pmWSQzF+3YNJuHJbXOB9O6eM1VJxBwCQlOQjUMzVc7eYvtj1k1Czt4vSdqKlQR9v4pj87I35MDZxy1ea1YQCN6G82P6SZ2fCCPLl8TqKboIMyvZ8Wl3+3dhKdSqQwfACSMydeGhK9FA7krUMgsNlGmS4E9ppkGBO6OGr0lF0xdWRbN9W9q1Rbc3heDCcE87bNXITe0uU0rnA==

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certmanager:
  issuer:
    email: muzafarov.olymp@mail.ru

domain: game-data-platform.ru
