deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: latest
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    GOOGLE:
      PASSWORD: AgBjqnF2BNV8ndgURbs/we3/wzOKx5gYP7dJiLM767yi+LMw/m9nQpColnSRiG/522DRdLjPxfKc9hRviYGN4LOK1vP08V9Xl/TDE4vu6K9jt4Se3GVTqQbgH3pv5xdYoQEBR4MLTZv6YamGz2L3okWU7Q9hAan9xpP7xWnLzjzC5UAv9mfIPONdcixbQMrAb3suAQ7p98J99q92frVN9SoJ9M6rhju/SqlHn8c0L0Q8lOJxHCsMsxNXl5K6s1q1ks06V3N6E8+nNkBa2M2Eh8bixOXsJ/iIWbwbixKxJdcqUZmbwToSnj2M8WHfr+6cvC6mKeSOBCqRwEZKobpMsQ1iVPQUaaMMWFXjapfG5ClazAroO7J/f2c7fRRVpRZsvkr422c3VVkolOS+L3/FfX4SJ8hrVhdPX4utCxUsTkGKdBu1yEYEy7pXbL8EkNwLlCkolIXDrB0Ee1E9oaLX/lzv5D1Bup4w5T1yWBdwDpanLIPyeCn9VMpbK7IMeLVbrbYrKhz94Rrh3kdSLG3lHUo6WNaAoGn38IKDpnBxKUncDBEryGfk/+/SR+LbPIm1c/T4f19GIm3J8dzuv8KeGCP8IFGoyjPwjX2fdfu5sJ1WPxdNniQkZleqKbTHQdV7vOegSMl1oCGRQKJcvPbGGyliWOTDi9xSwbySoUXKCbHhN9z/7KfAciV6U+szGhbYjcuK37hH
      LOGIN: AgDCNXP65PrfMB7abAfFxaq8L91/7u0QRNgx1QB8BW0d+U12fQNr/J3/BT4SDDHU2mR94qmi0zu3xaKeV8/C6XZ78sBnJTf/UxMWLDntWjtonZUVO/MLw8fLr3VrfC5K6KTSQIjaPNeDCenPWy1C1DIhMSx8bEfa8mbu8kNmvXo0bDORfT87HhEQpMkJLKjSwh4kBdyHOmOhUMfbjRGsuGeF52IMpJrJCHtcdRWxPBdBsfOCWurSyvrwKeRGMlyy8WB9tfmN+17bqV44LaGxds1zfq0UoDCUc1Wvw/dz0UT/vMrJ1MFi9+ppul/9yOurWyhBU2lzUe/EvSok8kjkSYcD91MNrtbBMddyoAopI0pdQvO2iaGxe/3hMqSZpYeaT/1ufpMKOfHNq2xHkIrey20Ipji5PO9Lwh5e7szL/UwQekGPRRdeGvqL+ig/zrYvC2vWACpxRyIbldoHZAVyoZBYoiVtjA/qcp6v6mu61fY3Apfacs672/W0epPHc9vZgkp8JZwCKnK/PsTxj1O1cktZWSIQ4VQnrB/V/o7J/i6vLXBKAGX9dY1urtf81SUzesAeUGRW37nNXWVzppsVOaU5PkyYMUgIIbMjxFTPb2eaq4vIxB3EJRDNsesGrKxmk6G9SqV0qtvWbVyU60BYg0ZVlB05vXoyoJI0kpso1KH0n8uSis2oqFoeqeULfSD5SwU4nzWG
    HDFS:
      HOST: AgB2+PBOo27mB0L/tHfKqlO3ZcEVKK4VlxJ4zt5UsWgWHh25339s2nF7FaDSKESIHmEjtjsJi1atusjlZFOie6h1zjjLhMjXL7jQL+rN264P2I8jLrA6jfn/S0QR1CoMtSflNm8IawGJsNQA4cjNxCvjSFEWOWum0xyWmco0OF93PmD0NBpVN/Ct1GnGcfywHxqCXMyzRjx3k/JR4YgK1tcE2a0uhmp5NQBSz/UDzGJH5XpmOYpI1IsNphylbUSoTsB/Or4nWkCJMyUUM0fColfrRrij0EgeOvWuFpfOiY7z0pXgK4n70j0ZWLrpKm7k6lgoOnBGT67SiVG9SQYZEa4hgOK9WLkQ/A3dXT1nxvFS8dikEUGHIs86vas32iMQT1PbIv1Fw8u/O2OzfQhiCSA5miWrj/35s3vQzhfdP0JoZdwHXrkAlfIKUDwCNYDZVQhmOKqeSQo0UmR66QW4YQKG5KqRWsGXWwCObWf9PJAd3QilWdyQf2oLfcbAYZ8g3Xz2uZsP/UZYENnBU3ND88ZJIuxs3SewPmFOfKa/D/U7HehO95sx8Idt7+ig1Gu273FmYLA/uN26r4hlAgqq68vnJBi+gq7kYN83gLhIuxZg1VtbD5MkCpkPQCvDk9jaK4jDVK+cM9tRuaKPpb+nSJuUwEnhyrBMIOf7OQBeGpnDpkWbaz14w5ptShAnmqe1/kHSsNygQMMoQ9rjCLY=
  SUPERSET:
    GREENPLUM:
      PASSWORD: AgCIrJNtWp7vKyrpjI6Pjk9FxI9DVMH1cJgiJcwKN0bXCuCVbAu+87h0MA9t5W9otRlAXNbVyeyXYDoIAqOM8U7fc3zIDuv9wheakuPHq6LzTzGZZQRMuF0oCrUJSCLnS2Ws8DDpBq7o3sInyNN5YsLOlZ2QxXUYjip0CQCHeYN7Sr6ma1dAQPu8LHCKE7/HNvOFOxtm1WqgKak2bPzsm1o3PrHgwpupMjIVdUaibqya12vI0EZ1hNmpNcFieJtCQh9S1obPlPprf+evm6NSbJ2+Kfo+FGXSkoEuwMfJdkQjZBWNcXsuzzba7pYKjyLVgoQGdyYIa1SZxcWPfJlsjF2oEtAOChROKw1bleZIPbtYY8C6NTicTPBh4w9sLbW95yZQJzxm3cfIo9eRDFfaaq7y7sTx1t6BoWV99zzeIIlN73+/T0XMXFZgYTSHAI3rE/AC2D2QARWDjkhLVfRXJysPQszk2y9fYrfr8a6N7CSg0pCBpSM3TlFQWSEYJqDedvyiK4CI2hEdOQtvVe6wbmPEb5Fy/yZITrcMPxFp8Q8hdUGWI0G753l4sdLkyPmEceIJ3uGB4vYi6ECOrPSrLDg+JoPLVhj2Rz1sJIILrcl2s720gmPOP1e2jMPNyaJMeaXGjx4o4X8u8GwaXZmeAE+KT8rfb7Fd0gcjf1YiUR60a10/KgfHhbvh+rr35XEEnt60Ou1V

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain:
  use_tls: true
  argocdServiceName: argocd-server
