deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: NodePort
  kubernetes.rest-service.exposed.node-port-address-type: ExternalIP
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgCyydIvU61OrU1uClf9rKCxuKSUe/0z2BKCs6ydfDalfUbCmyrwvJ1zHBqu5k0IXqJ3ghvY+NVrz/QwZdur+zPg44DsidkZbIt7DvbL3T60DHOCVYHUoLmXM65QDIiWIQW0aE88JAQRZweyLO1efDeOT2mQ58uVtu39MXCwrrEq6oDnZzQ9WIDw4+n7osmyFpH53MBNHu4SgPNmQJUm8ltRl+fgF36ZQLO/RWKclWb9tAGxZTViceFTg//62xCjAjrrHVtArIrA1RW6L1cHy/eyJljCIb1+hzI+HplOLMlHLG+SENpB50AbbpjH6h9RyNA/NsafthXqPJXBQuoUAht4yDnU6gH+FJM9Ugka2+57OFjxR56KNV8+dYpWzZAvyHguSe6e6TtL4lK7Q1Mb0tY+FLmZy+2m0LLrBp4Uid3vN4ZzhY6uLdj/+FdmugDKKSSYNhTskayEg53Wgvahv1BYRr6zDJluiYMLQrhRuqPiYtWKz1Xf+SpEjsA7UtcZ2r75UclFOpipANRxLKdwqPnzoymAOv3ohZL6QREynq0arQlAKyWsYOHLnYE55V9Mwn7fndij1LNRejfnxmzxc326sNLLMvfIV8DQa5Iu+L/2Vvw7wrsBcllDIwfdK9ITUMtluhEAXWECFUl1Oxu8ISFqMFG3ZTZmwGX+nfZ/1/giC8BJ1LDmftYA/mBDt8T6LicN4fdg5Q==
    CLICKHOUSE:
      PASSWORD: AgC2/FWFwkYYiBEbPhfzULfAbPjPTMjFIeoq+jpotYvacfJRI5S+FNoNWoGFHTKyaXm2SvPmX5jTHT+G2oWYn7bN2h5F7Ywxj72I0tpadjZyXdTxvtk/Ngflpgjwqfq4UQYBjE3e4w1gOhBPnEm15CBMsol+U6fXNVMP0Zu4ZaeKO67GxLkcS0HBqzCgqNl05f2uS1L8PkrFxAxTH4asVf0XYWR9WIdQQjtIdtZk1NBXklUZTeGNoQ1SD9R8fmiezNvxeiItvVCQg1YGjKudMnwP/dOZ8DBYLOtaf+YQdMFoeDN63BoTGWwTP/Xtoumc4rlRs+stxgKHs+hgXA6ZC7wIZcb2Vhcv+cKVjpZ5kfWYzyurAnSXlIMz3p8wjFMC3pFhNMkIMZ8eA8K01QyUHXQZy2/6WpPu7X2u737PpItLIxPxzQBKzdcuzo/vK7Zb27gr3zXa5lwZ0SnT3KaaGH3Z1FnIaslofVW9bYmYgXgvF6K2eU9W62guwFO4d8LH7h13DqKgvOnytBGwPfHX3NzXHZ0C/bIv74mipjMJ+Vgj4prxjef0NSIufPcpRg7i0AB+YUOXTvvx/552D866js5Q+0j+IrF38qCq52uwY0YDpp7PpiHLBPiGtEh9F5RQo4U+d5ujer2jmEj1sA5HA+zaaR9RZVWq5El7hNw+IBNHAvMnTN7/VKcqNZ8LnHfdbvE4kyDR7g==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgBpGUUl4s7svJmXs5HSBE3aSl5JR3tOvcFAxiIMDdSDDq7PEDAS8PTZXqSbZlWK/anhEVfAVPNEG6HA3hbgFALM6qXNSTGMcCMCZB0CAfBKksvEo47f9bhqhhXHZ9VdVuIMvcSd20iKmXtPRWDllG6oqTTXmOQxEndqYPdCuR7d2BZvJ5IOZw92hhxAcBd1G1Nkq1doKAL9KhiK1oRP4pltDvjbl/Kiyck4RrshfwTDAanZeN0R/yN4arm1fj3I11WPvDVNkDbqwpKqhw3gTntTB5oivwpWuGT3FS3gkRoKLRrTsVwoqUhA0uJXxYF2KVCUICTH1KUIX++O3/jZPUeaISaKbLo0w4U/2mUL9Bd+Bx89lEpsKT+VXNhG4ae5EwQQi4Kc+qJv3z/otgg+pkXxWcXp/V+pz7J5SVydTeytq37o8Z98ChK5IoUTV8d+trvsIAAPLJpo9FwO72pLVJkNuvHPhOpPZewo6pWYwVvSJAffd8UNGnKxnD3S4cDdqZGWtfyTEAAMoVCWVr9nlcZP9mcQVuUI7dL/yEGEUSYiztRrRxgFPlOWMUfZQ5T59ooCW8m9rjwYNeD0AfR/qTs66jzwdWZXcoL3plJkg0g/+G5pKZ8Hqe3QwIQZH0muQ9Eiy+y97Sdgm/KkRDj8+T2KRCp5H3bXSs8hbbr1Vura0MZx9F6PeIRI00X9FpEMuFCb0eM3gQ==
    POSTGRES:
      PASSWORD: AgBtLTdHjKLFt4+YXFv4y0jYNBzWt68IG8+S9zmHZjGNC3f/G14ralN1Krd9cUbmaPTbEtMYbHukVeEo3i1Rtge0bYT1vB/Vime0fDuZ8s3bbTmsbbejbgyvz4YUILSzNVgSXtUIefmKIFaVk13sFggytrnPJBgsiSdvkJJ0s+gq4JlYQKT57P/iVVESmtperUQSFlWs+GRpqf+dtE4W7/p/brvdhw0EGTGY1+dYL/Ysl4a7fBC2FaVrsF2DGhqGPGuYaOL22MavelSQfapVlYeV3xlnCA9lMzetvWGB0Okg0pdnzUnr7rxNvA2pTGYtv6IKXjxCMezaDVSwY79nCdakHpM0nmGX2pTeMW4/c04crkYvzgMuiuxj/27yly1KW8xXRd4DU1Seu1nyD0e+CiUEeGNkCNpsRwbajnxVmUYezSH7Jeipl+Iy/bQPUPoWtCESQ3ta02LMed4WpHbnJ281Q0sjdnP4SpdxoQ39xisi0GaciH2l8SyxhGUS63zWjunxQKm/I60KDprXCoUKR8jfd9MEhJvUurlB6sJBGXdQCPm1NdswIWKaTCOHbWbLRV/sf81kOVPdDtBQgycfE4qRPj1l70UPEhoiDZ11RJ8RbeaxkSjUW0JVadSVnsrtvON0eDHV55+E8PgKYRr7F7DPnuANDuFZhzgtd9zlRPtW+D5FHA/93j6DqGwQ6Z1+4lKKchiFRQ==
      POSTGRES__PASSWORD: AgASDAJjeh0ixogwDszdZDJJvBmrbBakR0M5wY6sUPgKckG3+eA2aDHzF8wRNd5AoR4wYf+C6MT7rgx9ffyFzBtzLCXvyO9KUy5/UOPOfyr4NhKSrsbfKFSHXiz05OzvF7Ur3ugra0Dw4M7IpzW4WR0qIs+47HhCRyT/yaCYhpP23+SsESbwhLAl6O8tAM1qAD2YUZHw8t5ZI4bJKXGtVVDy5qCnyf8+LqdoCyykBWd8TSYKz3ZmCbjSmm8sZ8VOzFCjVhgIoy1omMc6GHNGXvjmsbv1b1fjsazeW26EpAeRh8IphzXaSpNy2fCTZgTu3z2BOsKwtGncNeVVhUeHvMcJmxvg24qB86yrwcws3msoJcW9R/ol3aS/jY5+6RhzMnoDsQTi6Qh/2Sq0T06mQP1uUJetq+KKCTexhpjEu3iOdSrQyNCXEFKNx3UZqbt5jYVimQFtTo6AJkIevLZCKhRIgH5x6VI6J3JtCRmVqH/nptvJ8s5Pp4j/NrxKQdSw98LdjShVSCvPndG0a7JABFILEtGaUCSfWJzhfYwNgBVAaO15O9H9U93piSjleoSjjg3AuT/lhFP0jrJ8EDjiPv8zUd/AZ31gFdUdacgthAy9WO8NrR4kvHJnrL5Ge+LAszVKd9cSiGHGu+9ZuzhXhA7n09vjE4sJ8YQtxYrhF8jeDoXvVqyTGYdljMP64Hq7OZFv8k6cXA==

superset:
  enabled: true
  service:
    type: NodePort
    port: 8088
    annotations: {}
    loadBalancerIP: null
    nodePort:
      http: 31000
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp
