deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: NodePort
  kubernetes.rest-service.exposed.node-port-address-type: ExternalIP
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgA3G9Mt9Oq92zVhdLJzif1tbiP16GIAkrYe+3QyrI4wQdFTHXIvYszW9dBKEqumdZvLSS3i8ttGVyg0jBHPDZxRYlHurTFNvc8pC2XSjHIFqb0OPsGMjeoSQNbhNUdudsDN3+q6yCgyw7Bevy/nBp3lBzBTj+zK2PsTuSuiaUXqNkwuvpI5WIqyc2sCBLNeha6vMtGsi0w6PbZ37k4ne3djSpa/2nZNnRud94cqOj+cTuUjeZhHpOFRRCaKfldy4lR4x0ACwPfz3crJ3J89ALSv+G+WcgBsbr7cD8/aGNiAoKU59R2Oipsi53mT8NWAat3DnLUO7NOfp+E2E9y2IbAIrrBBZyKWQr5CzNJ/bNtVGwBLFtsoYEj98t4umgsNUZr41y3pTN93nMa5Sw5Ch/uRdy5XftMjAFF7euYaI1nZXiYRyQtR9lR54/kPfHymhK/dl55FWboq3aBHUA7IIT8ygi8qREh9IdLtfWhIjHeUrI+kKfca21xkIzYYNhHr0P307SRenvAy4Dgmywa4nIzaUsZokskC6+zqzmUrTEhSgsl9QYNHBjfRTtf2NbG/UbR5yspbjWNyJi6UFlFugCNsYdQwvLHWiQt0BeJcOU8CPTEqu4LnRIGmGVrwh6wfrmxd7une9GW9OcE0yd9EfrrqIVRXgz02v4vitInKchkuGSc3ozhlxobii5M8cBLkawOFqXzOIg==
    CLICKHOUSE:
      PASSWORD: AgBVVwBj4AHrS/Y/W+z+EnIV0BSEwG/d16HbE+h+bI+XjSqEClB8YcIRR9XKfO5fNliLTeAYY9pR6dH+tfLTPJvSvH8HabP7k+s2j9D/7nU/Z5wOGJesEXQ6KqIW+1Dfe8w2N3ZWaGxWHyvKzmoBM79KsoXzFwHxW0Y9w9TgglJPR1jd6RmrSQgEgNw2EzBJf1tAFQ05kk3mVMIM88L3EqdcDf4SN7Awvp1es1jZAoyM77FSg+OjUNz3HcIhCc6Pa3TawPbrmMNdG38f2iimsYJxBRd5/qh1wrCxs16oigLs4W+fmwwYyQPcMDAL6A6ykGdIqltRUe8QFYDyLmkjLVK+JRv2w7UBSeMYqihlBkU41Az0X+OLyeAG26KJZPSvYcZjJTLQSWKsHzfTXKV8XCvKtaFRonCsYFoQSaVLC0jzotjGBR1Nwm9YbzcsDjPRcg3+9oXhar/DV924ib3MMlpI/roe66roFbyFi9a3ESRy4KViedIkLblrd5p/JUx2SdynS6jBt4of8/6kWz5N4bz+Le4UotQ1oFZ97/nBi2QMBC/T4lyzW89oV2Y/IQcAQm4EN1eZQdPedEnaSCX2wziSLrWMNZ0IGbO86pcM9dvDyTA4KQHeVa/VmF72uiit8U/4DOWRD/gmVoasQpVlIm+bF0fGNJ8KDU9vlhJM5YJ1Ye0AA+Szw5KW1GyzqClty8HrQ0WgTA==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgBZfy+I8L3372CS3dXR26raAaQ7QkWlGja/9qUDlVkrYkQkuihUTOenFQ8GMfeUuttj0WwHUgOCNdTTGMpClrnOpDVVh73P5fTXsaPmrrkx02xeefdwLGDFAoRyXMbk6eqCD+B1zh8r4+3vs8k4bFx336RVNJgwpImwn3sumADGLs539DfhoDM2pStlILZppnbFiXvWSg6MgWaBBXDwoBkRf11MVdf1nn/yIsv5THbSCEedbK7fgK2vVHWb2lGQJjN3Hz3Qu4m3EGlM1bNEufg7OmvmCYZP511QGClgkg9O6i5y/xkIffJSlzJU4Xr028gCRbRHu/6ODBkupZHBg5MXCLSAbaa2Kl/k3kPppiskobzso1HLY1aem3iGoQ7ep55K3ETbtRwafWwNysl3WWHjHKPf9/251FLve5BhsGfQVAJqrchXUAbl1sBKRpdPf/ur+ZxUvFV+uID2uiiz1Tlti6ZBjkcocNvbxzNmw57cFysilfl3ilr6d5LtYICvhPaXhsn4ZDpvAGCodOTDDoylS3oV1jRYd/0psl9QpnWFtfkLJZt31thvvp2xjd3GsQiYge4mz3I7H0GE1/45UPWigSt9hR7+PgBUeoIKC6xwEJdb3HFg8WfJnWx7pmFA4HAQKXDV0YWFejMo8L1JMyCZJ0Qkd+K1lLBDYFLHB6xWFczBvxc13qXac3Fe46O7LeS/5LNt+A==
    POSTGRES:
      PASSWORD: AgCNedUP8yUU0IYwr4Ows3eGPTM47PxX4yOREulHKMAMuaxuvZq08nqsfgKeaQqlIz5zQhVoilEmgaLktweAcAd2f4O76QqMBwIQzlhkdBV6on/sKng4SZrrfgD4TuvtTzhYqIOpDaGX7SE1vHG0KdRSfxZG4PJBsN5R+MCWAtRNr5pbmtbP4IPQd2qWjNO82hxfMGNtd8s/RrYAMhZgkcxcdUsU5P2cSIcaKey0YSg/jSIUFsXDlwuH1jNgJyKzuhumnI+1KrjiseUwb7ig759yMvhJOpLd8I+BdTaFEeLCNzl6HckOj5Qs0q/PhA8/G0jHqxHU31JqRPeK0BIiIifdJagayUzSxlzNOSnVgK8gCqST2a0xP/1mx4PiLAc4zN6n5pUlRBnElWK6UPeHCNy9cdsSNzRik79QL/cET114JxIkqgq+7l/VW81UcItXDKGZwHiCGLoSX2g92U6eNsgs/jx1nRlLK098IwL5CWMACGl6eFYU5DEbscMWF5+i594S6QLgWI1JWrnrmqNzRrZLKb1VTrFD96/HcIR7izYcOW1/I/hrsfa0p845py1RZ02g3BPjyZPknw63aeOTwZ8X3EGHXjavakR09Syg2hmwUuK6JSaq2MzqNWvRkzey2BqmH9Ob5kyFJ9pA1Is9af5lwV980LLCbUwoRKJ0p6Ym7G5PBUFJJRjJ1pGNzeFW3200vP4K2A==
      POSTGRES__PASSWORD: AgBx9mYGIHGjVD8VaJ72AzT7WKQCikshpo2yPPACDAMDiwBvTJSdxutITT98ikqD1OUEEsUqvxlzvjlVBVkDCebDvRsdhN/GYQqvu/7RZIrmV3+sJCol9x+zpHzgURUzieDxNRYwv78swGnzz71JojN8S7Yw3qEyOCP5/mL4Udi6rlb4K47Qfcf9C6i8dmt3GhYiyhE5VFwjK1WWkCwPjavCjmX7zMjDxm0xr4Ese0WBqS1tY1bvl2eWkQ6hsIzlfAfHWVtK9aiw82GkX7ZHTEB4jZ/Fp0tMABNyP+/u5ctT2kpIpaU+RPPIBBdjl62R8dnqcDwNnBeaKxP5oz9N6sfne9ZFJG/OFTnr/0R9eJEstQ8Ld5k40J7IvJEjnBfDxVkm60ZYjSHmt1gAJQ1GxLkyK7hjtIL8e/oykgjQg1F7DlsIUCuDz/tF4ANgthSW8GWEyEVZ8ESJT2j6kr30UvquM1u8PoAdQXLjalenLJPgi7C5Hgxkv3TmdGbZ0cqsgqPlZhcYiw7jRtCOuH6JcZAAUXpNBjPsDznMs/DIpIIwulMZOqP4tnW2kKtO7pYnHRuOiVgC0DM/9rZBswYdjP/qQsowUhf/bSAxMD/9xAOHqCa3HDeS/qjBi8xLcMmY9G+yLluxbFwFhFfjCDv8akmZr8jzF1u0U/E71pEmL3Hc+v5PAO02k81tjQvY/bWucl+YDw78uA==

superset:
  enabled: true
  service:
    type: NodePort
    port: 8088
    annotations: {}
    loadBalancerIP: null
    nodePort:
      http: 31000
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: false

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp
