deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgA662sTAXfKYkQ35xb7Nr2yyyFDRvhAJkYRVd8aotB1ewyDQOrsKuF8lX/Kv5v33cwfvLRpEoH0Kcl+iqB0PrDSKVPSKu+5oyoEfmdVKqfsNuu896aETYOYCeMSKCOFxFGnbvp2eT+SYE4OrL7X6v7qGfktYTh4nE6mv6oO0JFKkWlUmhU0nl3LswA1fDNmVGmZ/6madfy7OXinbaX/lHX5v2NgouqsWziLYEdD9jPY+yl6/CX1OrLdD7mXlZmE9JAyg7gK8r/0j6yBZZjzfGU8WyprQO93agMTllmmz/X8ZxAACtnBzZZ94lxzQjKPOAnpfFyyV97KZs7oik794rBKoMpH3z1/riiCuyGLf/wDjZvUwtYf1mx5Egmbca6Du65rCIvNEKF5gj6AdEubbbwuX2mr/i3Y/OI4wjoxtf1hZO3JTWPkNLHiYLmxB9YCSSuphPvV3Wu4JtZ2xoRa1ikASO1jKUafwPGwE6PWu7KWzxZvPAjlsHsqJZjnzij4BMcMbfoQx0fqapXvwiTlwenPOP0gPxrEPq53HkgfN7OCRj2kyasbszGYCA+3N0mUHTzZUkVhYPpFBwXvFslikmfgIMvz90ZckigELqnbxEEmtzG45PWR7BMFLamtc5Ntv3hVgeYeU5X/CMZc6kjQppD2gwQ7LMq9HZG1TYz8xsiPSEUcbUA4AiqUxcsjhcOi8EpCPb4WrQ==
    CLICKHOUSE:
      PASSWORD: AgBJMA2SSyASFYzWagDCNcF/f2sP+3kkLMh/ypOQaJAVk4rKuSurXJXrauSYA9vbPuktJGE3y2ib4BC4duxnWChSr+mSDgKiWUIK9PftSJngvf8Fo1Jq/zwcBzT52DAKC+BiPukoIpY6vP++8lgvJv1J2OdhHH+43j+l9nGrChy/Xezd2LuFwXsSdm3ZPy7iKpS5qhLU5rcOQ+/wik3mvMX8t0kM9wzWc47xxRSYQhqTvm4hNmqin96/D1QzeaPd+AxxaWQ6PQEX2HL08LAROP50krtnfaQ9paTVAfhkueRyeKTebBa2lpikzqm0L2alntnrd3IsmX8MAfJVVkUQi7f3Vs80cFBP+z+o2PfHG/0GLa44Bk01FtT2CGlvUvZyHEfMaDFXgdLHiFT4eLNsAbYau2EX1vm7MY/6wiIJ/lgUXvIsr5DZm42LUvH+PVzF8mDuJqO/43fK6p7xN8WW8QJ1tngO4HlXMlxfNy65Kct0iO0fZF6l/cd+R+xUVtJhjIBxr9hdZ6URU6DUYiPeru0HzKbe3lkrnnbMJrn0uynOr2g4rF529Rk+zlkHIgXxO84x1evAJl8Y0Ryj8mojRfL3EnokML0zXfXR9MlgbPz+9BOAocvZbPElc9wODH1Wk5tt616tAEhVVwDBcOCuxPXz18QG2gZtJJnmMhboEhPM56RdKwSLgbqRuYaRuHdoRhU+hXCp5g==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgB5EbYaIJlCu/TxUWJKwcFp2LHbrEyVO22ZZeyC8dzk9ACf7e8GowLOWhxH3cqDpQTvMYi7dnT8w/GBJu/6jJRYArg9bb/ud+ZDs98AIdmrpPY4Ak52kmlE33Kte4BEgC3kWZMVQbeuvzqiOCuvTzIde2rIuVT0F/JLgJpRTUF8eGGIyPMdPh01XbDb5bye+j1D2Lu/9OtxB/P3BVQIQb7T6KtfDSj3RSY+hO+XulXMd7jM3zYvUX4uOx8m0aSEedPyhbFKhYNn/1yk1Cw9vOSY+iS6300nxymIXT8fCVu22uiPPovGJSgXbClxCuuKDD3gR92oYg8LcXqk8u7iS7mUypLHQ6WsPXBoYKutNcIAXQWI7koivHon/gJvUWo0XLrN4Pj9sW7vUY5QLIpgyvSbGzGExwLc2PnNsMJf7aJe6t/TsiOb2eHxwZiCo3bTa+Ldk2ZVRYn35RnlF8YGtykMnrs+ID3BYK2tvDUwJhHYVUG3kaQgTShegPMG5gORjOTwTqwOxd7B8YyFVTHedeqSMti59QDV/K44imjSsM2DKURRRsMoZgMWwwqSf7Kx8txFGXN0GEvP5C0JxhGJw0PRuv504tyb9wV7Y+qmCgEbS27FUGJqywlaf8sFGZ188FgNodUN7P9FXrsAal9bXXwIB8Rutgz9s9WYzVJN0b8lOzYa/fDVl9sqtsFi+uQx1MSu0NH2kQ==
    POSTGRES:
      PASSWORD: AgCL7gW4QFAdSWLVggZueFOnznT2adMj0iWT9bhgjhxWqlnyQ+m8+Ter/zYGbQf3T7rCYe4sTYbsJaj3V22mTQ0rj8RSdaRox6DXYuma4VzfN78HsS70zS21E7w3yje5QGikpj6eMiiOTtCaPxkK7WZ4x6zIK8AR7HRrbDtGBfxqX2tsk2NDNjgQXu0rqL767uQBLs2IXYzyAwR20NuZ9zzD3u5Q0wByoIJnmDyMsckD+8hPstgaIeCiuqa+B5PnhEDU+x/63+QGWWeA1dVG4zpI9qa8ekbf5+Q7aIMIwE+UzlsVJIA3RfIo8V5mKT8HlcOwXI9vY9x6RlBhMNBJ3AkwQGT1q1bhDTBYzuqEgXeDOtRdlHMmU/93cFOBWvl8OaZQ/Je28EW+EKyG1RecMOLwxNNIzvCDhBl8XiapJaQwKQfdktdrlEXnAieYv6TgXno75xJelk0zSZVjYC4RLGRZB37CkRpaPVKhLIgOSeJldrpi+9G3Pw664A4YGftKcZMyGkue3Ktet0HFtNtiq2xMsqlRkwcS4sAzcdMTC+QRL/xF0a4wYCrDQ42JaYBt4CrQk9OTDtbcx+F62RtpE/kwqC5tkPI5b9yc7Pk9aYn5mi8f2pabWLb8KcUzK2sRZj+IiaRpYeYM7g0pMX0bu9Bw4rRuan5sMw4N++UCCu68+sQ7BIz6++sUoHWLRTyOvsHFCqeNeA==
      POSTGRES__PASSWORD: AgBCQZWhkBr7n5Q0jmiPJktPTwqBcBzyyEK9kOJPbOl0PXnEpCJrVUbHQLQGv3/CoE8cGVqseXURgV+NaCjrwDczSQ0O2UXQFFk3U3RadJ0BBR2CViduRe2OPi7nca0Rz8KcjiMN0VhLd9C8NS5PPaoQbPjUfQ3TFwsa8i4pqOh0rh0sxKO01CPDSIWrsgbBmk5MF7abNWYu48lFzHodI8zDqu2xNrChP9Yy7z1F+JtW4optfGRNV+koJbgjzMqkEvzlcb1UfpuJeIAwnC5RQ9C5lpTzjRvCndOmt+HBkJGeHzY3xizaxpKQnj0IOYsTM6ti8Bx0bGwUFs6b+pv8noiPTr98gm0uf/6FQaYTEjhxjR08NtwssDhnlnTtPG4uqBqfTCGC+GXiUP09NB+850pBkmSUfvuBZtL+S0z5qroO9/Qk84OyVCstCOMSgnHXfX67Dx6i5h/iAuw8XEzaN2HUAwyECRPelxix4GxtJecT0fjB705QhMCXofeSFFtgUjBhtmJn3HttWpVU+F7g0yJFYmdf9Ylj+0jbBxpATscN0hSC3PaqTHdAy8iKBrn54kCeib0PW9sKpCEpTsJRpr2V9oxWVUyFUPanRwc1TuJ1lRl+FeEpkddh3xJN4tqUEWbRB0SlotUcgvYtimldcRAN99OIlKvCd9Ggs+pUZ+fz5mzouSVNUmVL7HttWIQa4AOeOTwYsw==

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: game-data-platform.ru
  use_tls: true
  argocdServiceName: argocd-server
