deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    CLICKHOUSE:
      PASSWORD: AgA9+2FUgtcDDisXRJMaF8vvWUXmJBTbLHeLu8Z9/O1mwDb8Ad8X8tcCgLm7214T/9OrUKAUO2DoUy62PZ6iIkB5nAJNWW1e3TCYuM6iRVUkt8uBCYP+580QnT4g09jm9a2IHaKF+ipOewnpwVpK/vsfuLuFd24Ul0gFU7IdmSnH655ABCs/W0fx//ZB09bQkMh+4sWs4nv8vANZmmMfJowT8d/KrSXOKi2UsViXz9KTvfbtGNl9XXuE5KUh4Se+YaMs/FRUJ8hHYOGEm+B8YC8vcPpChL9rIyBe0/tLJt/E9OrFIXiwcoH6kHtps2PGLC2aV1Ol1aiajJqs2R8qa2lMZAzAJo7ILsRuPp69MAki/Z+FjtjhXzm/RCwMCKFpPIqw+gvVlQE2vovKV2M0S9VPIn74qoIPfuauPHruTS9lITn5tbhBOP/+bsRbQs4cGYHwjB12GVldTIl0Sx7n6TD/Yr9dKW4F+UkubkXPBlv/b+RbvlJEPvEET3rwHcvTHhZ/YYlfabw8V9+XjYF3KOKRL4MKfG6ILDjY12nuRN+lCIGrUreIMiJgiFahqf9Erbjm7VAbj+4pvLi/n14Ggz05Td+YPoGqse5cU1FKDhpFJS6nMe4oYkFdbEBOM0sw9Wj9Am2MTWR9pQ8sBLvWsz2AuZn+AAlJ/Fw15Faq/inrBEDzupAxuW+wm9deCKH5DkDu5Jc+Nw==
      LOGIN: AgB8SZA96Id6pZEWaAqSCwhh5H84Nc0WxRpYcEWTNmgHtu+V7a2pdFPO5ZGQ759crCB13tDQnQi4p26ZF6AySharSfXk8Ppu8igBK/f6T5yTG+ukiy8/Y03O3+6dPEVJANxsRiuGjBOswLDGpHiS35nU9Y8ruJDIumEUwJ9iy1dNQPUMckfzCH5uPyLXuz5ekOYzDur6ZhJjDOa/FGQYCrE65jA3g+snLEbDsK6ehIn/Xe7IUHusGnwWB5XQsJR0eq3dX7kXS+BMgts/6u/zSi+pYzZ1j3bz+6Jh562dMXLgR9L+ZMU3sanchAgGhe0uPS9elJgEo3MxJU1IpEVm5fDMRiAxyf4NYU3vKqD9NRYQQsL6n2stz/ai0569H+9yRLT/fy9dM3XsVNzOVgiq9vlCn9qfM/P0aen55Ejw5tNsOBLCFK51uDIp7BN3SrJ1Kw5SNqsRBt+F02sdbOyloQ6aSdXCPh7V7t9powTwmPobpiNDZbHdUny1oUg9KA77wFSIot9E22t+RQSvzSlvYI9umVNZ9RAf58IlrAULbEr6IdQv0zcUVDtayNj7EGEHPAJwPyEeoxyBcr6bTPh6QksuW7Y5pIoF25TXTbnEZIemgPjixBxnHq7pP7JqNRH1R2QKAnrlAUDmvI4zCq1i0t9uSTJLDtGRcDox+mGSEfEcYxXAiciwIG1B54gMg3cTG7xeMwUmipD/MI0a+1OO4btX
      HOSTS: AgBvEWMdNkLBem0jwtcQirtL8pM6RwUnD2cnb5fy9bHSLWboBWwnAwy/FbvpUg300oL2EPPJ462KCZEeyxnotdSBC1o1bSZUSH7quu+FMYJGJzsd6i8EfjvSJXbzAPxVOT+FK8McXqyxO2yAJYy8AyaD37KakjOBJNHyv2UfR1yEK6Pjvo5mjmvmmNwFMdmMudWtPKhUPvmR/1MfFG1v8OuOYf09REa1o8QIIHnZEmOP8F6NC0zSONb/bprdqqWl30cmWG/j23w5YmOOOQVwwLU4L7h1mPUHIdNpRMRd3PQgAvexkecND+pTMVkqn94dqzbTT1OjSR4jlia9o3aFEwmh8wTo10V0Ah6+qpUKk90npjG87gOWvpwBMPectmcCen+RKJnEBo6H/MO6lkqI6fYC93moaZc5xZ+U06oaIKkYJ/b7UM6kXCOCrtRyTSuJghhsiQ9e9FdB7TixyTArepBOWlOpNT1AA2GDPSwujOCk4IcuFoThkSN2ubByGl/es4zRVp0FF6Py1T46KdfKApKhTZrA0YZ9j3zAoWcLWi/rlyz3XhS+On9roVtxii2uR96XwGNjjik7pgY8WOLXdOoAsWkm+eqKwrnbOUTT2txZG0QeP6YWEiNbwuJ7xVmtPNiOUlro/anjQrZlhvvKlNM6ntCRrvhKyWp05pt6VdgnNWw6vme3g/hmVf6im95422kCS5+opwCm8JshjdiSJNK+PwCR6DwbhcgtBisajhKE7fEz8LwBTc5buSugPbw=
    KAFKA:
      PASSWORD: AgA6wA9LB8obivae6QvK9YodSxJLISWr8H4RM0nrxeIJaE3xDvDmetgKmaf+rE7jhbYJcnk2MLSYj+rXcs4k0i7TlolWir6nJFSvJ9Phdf7fYIWbbfRyw4Okyo5IS/JQXHXDAeACabvD9CDqbxOyH+SdJwtKzkiUHWsuX2s7DLjcOG5tYz75RMRMRT/FbiKrjEfJ01D7M2+3uA8ClCTKT5qSyn4h91Jo4oMuthvTsYZQZvtPFuyjczLH53tlXjwf7eto/ZI4viYJ40dmESE8/pC8FCKS5qF7Gl3Fh4HsreaB9paLqqhO9HDD+Dad3Sbr3xUSQnOhem5657iGlk/wqCCD3WfvCDpLggkNcohgtk+7kPxXrgfKUY4V+jeLAjwMumsXxuE+mqUCtWSNFgDST3F9NUDtsvTSfkdPpRFxoWDmWagwwH7KYJ8aqyEmT3wmISZ/OdHzg6loJ2oAI2h85cfHxmpORxJcklExXS6vj9LxRCj85OKAquty8MGEP6tmfnKzI15hJboWxL30PfjVzJqxCJa9ZI/nyCXau9ICiX54xlIx1EbHz4G/poVzRT/wRiU6QWeBQaDYBZs1oqZ5OdlWSfCt1cnLAUqAmj2czvgCeS7mk7FVzthcVRUicEiQsWKAhoxguKkde3Gg7M5rr2B2WgxWwLEB1evmz4AHaeeVEKTViECOA5xksPWkQRVe24e8LHM+Cg==
      LOGIN: AgANLif7iW2Mfcbk/hcKkMThPYx+82xU67bcLgq41ObeLZI9j/+Ywy61MYfa7vX6inUcm2sg4bbYF2UQLau44X7w/SGz0QhHPuY75MlMSi8aZzHRnIe4+397mhecW9Ghuvk+XdbBX33/ITTJl6oQhkveZ4Nrj4HWgzuKkpTwkHlN761lW2mwvbtCq9++hI0Wv5/u34iu8waJngi70lAV413eYJy4Uq6iWdv75igEVxmZedzb6dJTnbZtiOzsMiOOLfHssOR1qwqF6oX3rf03bPtFEEbXSKA1IjaqaMtyFOdaCjjyIhv3z3X2UEbz/JVHnJfZYNH0ZoVU4WqKTw1Qb3cC1WU47YRjvYtwunSZfBKvQAPUACNoikBn/nCugwrDbCbwu88/65KvOR0z9esscJKBLWrIe9FCLUvziBtJuI8lakDKlhLFIkHJ5zGBaAJqlmgvfmW599LS0B5VzoLh0UWJqAmtGp7MQ2UuBcvqYS1/lxETpGR/erRzJIyrSHZvq0bEIKQmf4yKYkeGux6Ll3+NdPHHZvDoarOMjJnKtZtm835BEk/7h6otBkN2GyCVFHvYM5rrXSE0LYv3N3Wy+nKZG5Qg5Kv+a9pMp0PPjeoSIR9R6Uz8gX2DWLdVu2VMCOuLn5xepbZYQRKio3njomqUIPc1YbuZfa4IMBqCO8r8aUmgZBX5X6S5FVXjJAgco6SbW9XOl9bKFQ==
      HOSTS: AgBQjwC/j8KN9d2nE0d/exmtEBfAfZC+gkyoUuQV6+JCBQXD/2NXNFmZPeVBoIjoNTcY2jP2I0CiMG6B5+5/txdeBAjW+i4kxm6UymPCMPNq61nMmJMHqZJFZ2FWwQwuKmpnkNUoWJjvVRztArzWVCnyEjck6cJOV9Q4rvBKF0g3sVkJ7Py7sKLg5tmvaNg5nHsaYsSYmAbpJpY6rOs/XET+MFz0Sl2LoiXfcdHOq+PiK4UQYQgmTS/k72FLSHxSgHpvIHJdxx1SidVn2XHKerYuj8g4uz2LGokwrpcDjqjBzg27NNi5EKz4TZcBqH1ph4dtRjTqoP+VH0Ad3UJBM2Ur4F6mTRCEQHat6ZXOcN45VTj3f25WkrhfDv19Njw5c6g1W5X2k0lJrZneYpbwajAYCx3uxrq+5OR+fJYb/Bm9rhzK9eDehbjbbiOzVx4n3hyxWNY9nu9DDM88+LAy8ASQhBijjaxNP8fXob7tfJlb6Vpk+X96syT7epNxEP+W+JAxzi3LhtnikiYwJ9F+r641SbaK+q0Q49jZtrltHD595b/s9AxHVgE0gTZidH/BM3edh5VDXdHoo/JQNtR48bUOalpNhWfF2fkAclGt/HhFFPYRde32cXkb6DwTryMa85AxyOphtiD4lrFifhczhE9GzcWTYibbClGDWcHVQLgT/cq+/KzNK4hY4bdB4ttN3s15VSjJqNoWXkVF5uMHvZ9m+c8m3SNtEkj7gBgMhbb+QsM5X2KZOa7r0oYC3jrzSdXZtKfn3hJk6e/6TV1GUivc
  SUPERSET:
    ENV:
      DB__PASSWORD: AgBNSib3PV+dVMKpGQi/9MeN5nx+OJWpRN6MJGDXWGsZKHj8guZMKoEm+BzrMDFS0g7lXsTR1n2dPm16IGneN9QqXx+2M9nXWVP6A8aI2D96mfkcdkghRVT644HAhOsoJOLjhMVu73K+V5yLlR66ImNdfhiyxUAVyexyFfXfixPkPv0W7ARPLbukkOeS5W5hnlhdQCQz8LLplEw5DEwm18OniA+RsbNHq2aNaTfYd2yLkmaF61vam9liU+yap8I4837saokgCvrVG+m8s3aKnDfC9wCH7YYtuyyOeylkn8JvYzAVZfRIJa/R48iMK74OMGj6d/4dHTGJaaQhGHPK2+SDujltQssyh670mkMX9vBbjsxuii7zw+XTHLVCIYsMdSFSnvFwRDCVJER4fCEM2mH17RQpdWiYD6tYH+HO2ZyrTTWT64stHvGmHvXwNTzou0m4cd9V7ueFaAXHnOXGpsZ6yAH3uxpEXs/11HlX6LTcOhnqjLzOHcbYHUf2qBXkYt/eWpj8UhCcU/D4zJH8Ud1VjApadpGVq4Guf9ePM680LydiYWNbAz3fuY7leCzPrrZ6YmXaKfNrQTdi1uaS3K2Z8i/RkXDex3XHDD0bf1f6vI3T7zTZlKAJToTE+TSMLe59PHIeN2PUmCg7OPcr/j894OsmnrEqdon34Oo6yawRdcCIMNAwv/PUG9pWEC92AKrvsoVqxQ==
    POSTGRES:
      PASSWORD: AgAaVnTwie6cB79yBzd3dRj04iCwYi6+WLoSfjmpCPzvXFpk9JW72uqzY54+7SyERVJStCFAmgEBFwcdH8wR6WrhWy/J1VadIdWIZcOuj+BEDI7br+R9xxYUIuBH+Ij1euZ45DmiDU9Q19FBtkI3OgskKY0GFkaTs+O9VV09W0/n5D84cpqu5J8TN1mTkFT6mqGS/gDwzCD6A+BjWgLW6QEIUoeRTDi0lfyG8qtp9kMvX8KovXjjkW87IAriBUpQzZvav9oW7mh2Pchl3V4Tez1+SzzumyDWK7s8jbyHVL/x80B3iMxnKFizNRUkVwwfGlYKGu5wBk2eRosViSHpOlR56w4TF6d3Z4zBHxrh01Akj0jbJGw2m5HbsywXHPwGRw48n4ORcABQFXSAuOGIoKemN/qGlWfZaKmwuxQpkUH5RbMevLBdURj7QFxD7LJkDDajnWOeqx7n7nGejdQ/Snwvy6MXr/n4gbCwGq2CI4BJwtpgorTCEVrDpfbvnapxoYsklcaLydtkhhETSpJO8FlZxQcg0uHOaKrptoWXmFanfNWRam1vJ9K5tI/hn1cnOrI/kYWIFKfL9UhmdpFuaiGkCmmweZtQvAZRSuOxptPKUBXtXuURptL22mbaleDB82dzMPC7D4TG7puvn7GXNCKJ26b0avNyjDLAgQOGkRO0bGyYH3IZkh2RsFdS6beVkm8VY9+QCQ==
      POSTGRES__PASSWORD: AgBYIPlOBnHLN2IGQkZxRxw7D6Mh2ruTlxgLHscpMdDWd+GKM5zOCqng138YK4YHmuKLGhTi9dbWjH4ASpFZlyBMo1qHPnKGuTWY3/8DOj92a+dgjyd8FMLVcJWp+zdkJSNREncy2gXrPOP8dbxegWMzHamx1m7/F/+SJSIkS2wDpJnNSgn2SHEBf5CobP2MYHZ6cZn449R5644ITcd/u6WFzCSi7Eg/JF9dfFjFIo1WInucjRNO7LFOV4I0XmA0IxnbRmd8hq19iXskTCad+7/y2kQGgOS+pJNK1HNB02+enobXdkt7IGukC2PXiMV9efJ09M2SfDnV6ftqk++026sggM/N81TJuaghp09qE6de9kc8n8Y3pcc6ix0JpKNvG2gWFMNyPrtlXp/A0lpQ+hJcSc3Jisyu9pe+sOr8JYY/H7jsqxM4IVbnHBcM5j4JuLpxK4Z6HmrDvsU2gXadtCur4D1Ex+atrzGjkAS5/2zjU6V9LhOkaj5o3LnO/eExS7getQhkga9iPBj5tuEhIsl+f+123KXhzJFZbNFKNRzLDpkkJHWJ3l2Q/fNCGdDQiuZVp8aJNOe6x8fJKt22UQ3s6A5gOdHpJfLfnGcbkx31TSmCuS9b5n+gMD62IiM6MQT2wIrontp+aKtJXntmA6pUvBO5VUWgAY3xAM7RfH4kKfYeXipGtdY7epFcHomvWHdeSAO1IA==

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: game-data-platform.ru
  use_tls: true
  argocdServiceName: argocd-server
