deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: latest
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    GOOGLE:
      PASSWORD: AgBntL2VZ4+S1a16weEb6UFhTYy88wv8YblzEMxKGjBxeiEK+gsuLHk7vLd2+YLqDzwaLB5BYPlYq4I1JQwg4IwaGeYhuwHFxG0wJiwfPBtoLet92F7brN140EL42Q2Zga1c5kWjkVW+hgghVtjPUySa+YdU+S3SDB9MPHuKQKl2dGe620jT/E4ksXxpcLKX6YbVzkBgsjE7yK4+u1hxQiaA6DM6bKHD2cv1MIhqMz7RslOobvqepG4LCeYcCzUu6b1zduUwSmrP/bgNqSez3jwl09OTVe8VTnU+Mi1kScHMjyWaQnk7gMZS20HdMw8a+YdbpSW2FdecZKQPBmEkXf5tXIgDjAJZgTrQeAMw94NyPgXJh5tlfvkG1EgBLQpoYpw258EOwthAbbkJT/o6uhLvH31HJ5Xo/dCTC3xl4WHLmm9e/A8RA1aqMqAovZ8YAqC32/jUsQSf0qT61bC3moDYmrjOVyHyTA8jyovr7FbaMmUCmHZBL3BCIQz1JiiKzDUvb8Td9yYefPKs+GDC7yEWvhkSJ8BoHfDyqvEO/AlytP5TpWcSKw1cwo8Cx1PZc7tdtQmDOcSp85DseRYGbe5D/nmNv8/oyzMiEyv/YPkYcTplqI6OSnXwUj5mWzksYIqT1VQ1ZRM6OxCAvuIuQQlSzuvzcJqI5QmQpk6sQU6IoUTbsaX8UhVc362MVZeXBfhqPbkC
      LOGIN: AgCVIaQlJ4dIVh52U1eQD9oG4YYiel4mLASx3VrgG029tAB1dMblUPVtNGqm0HyALloUd1/bgD2EYiI+rzoLU9ww5p/yKXjOsjGaWy0h7kUEL33JVU6gfz23NCKjHLWaYgtTYi6vRDjAGkBt3VjTWc7GTkEfFuNy0mZ4+NLRVteb+u945HIpFTa2qH4xA1F4LpNQMW7bFxJYCaW0rzWyMpJQjeD3SyQB39V8++0oYRoNhdEpnrDD/2Z66vmrBrwtpApCoMAMKBXT+KQzghl+BOVlXF9fozJYB6KcBEdi17g71oRGNl1+fGr6nUmxW0MgsSZtW5Cn2ls03o4c4Tr/V592Qys+USTL6Z0+VsbSMUKSZuCYe65sh06M6BgYkxChPEwjjF0p3ryIOAHQFS2hW5dMlSUr4zgZrGSWYCr63/iO0K8FqJCd5bNkadKm5QbB6sjrH+Gg46Sp3bpspI19jQFODw1neb/EvbfTQNdjWmReZJzSkIqaiKQPE1dT7gYwxLs5vGyDpgOUvnvGYV2BJ+ftBUFY3SEs0sE/ecSja0B+Xo7u564T+4N+6UohV0afsdE+JvENK0vDX95IeHx0vy7qgRBzikKaE1OgL+/19ShX1h4WWF5I1t4GcFcB14rxszC1Vw2FDNw5LRpjKfWCSZdOELK8C/fYbNmieycA3yTG+MYXvuWf7laMMzBFEggMJjrysg9D
    HDFS:
      HOST: AgChlnwh3LI2L2KrAEs7X9iKs+7on3OuapoV5FMXiOucsLaPwA1jXGs62UakaCgadd4GyumtT/tl3P74HSlqOCbrtnP8v7h0NIDDYX4LbrgUfSPxKWwDetMt/3lv4BlVsXWr0Ma/QANE75uaoogvWaWvvZOYBgK9O63VNh8XKMrt/yo6VDSYMRGRiQvDWDnwArWqDguZCfEadJ0qNFCa21yfNWSj0fC8qrUP4AupUM1bqUgGf8/cLXDRBvy6ea8NO5hvX4x2NvJ5yMIZS7Y7EWxoIMRLpxJQ1TK/TtK/LpBjxU8kOc/gFsK6Uvuyt81+wu5EIl1WGSYr+20I9YFAi7tiVBYgm4Bo7u47fxzneYee6+tFEIjN4zown8Wc4PF3sda8oVwFZ9coo7qeDxbkBj79u89hwnasOhjixSXU0O7Gp9JsaePbOKCxDb0nzBmPcq8KlneUycyz+435U096chzkaQIox+nrs4VNB65uYYxI0r/el5hdPtv2NoglTVrcNdX33u6du0X7X/0BeQiJAcDOckVQ8IwFS3hAFdu+pr+xmwpvUQ5QfQGY0gr5sKAEAeG3Ebav7oTeIEZz+uGPRX56IZUeWJ5/yxwyHPXLRqUHVu00Bzdnqd1uujZr8RYd7HDBVCLjTz4Igv6ijXOoYSTgKx0xHOB3UGPJpOWMPENX96wLUK82n3K28gUFK05qKnc4PTDjtAPwjF+SKWA=
  SUPERSET:
    GREENPLUM:
      PASSWORD: AgCCB717I/4DN/wOsvv53Q0o7nRon029l9eDYB/QOC8HRkXnUkhaREcszJBPFsZNiZESMa46TOlsy3mPcz+CIlun6EiyvofVR5Z0FtCUWMOYYnRv2sFc8z+SebOHFzo/FSyEmgQ9jmhq7yUMhF+WxIJbD5QsaE1rJQl5er06aPV/K3pq4yaH7byWojzLk69pKrnpCtEFw6X8e8DZuRCURGAp6z+yBU3xIOfcbU98SvGKxB90RHEcBHHEl3ZJZeXv2kgj75NZl9wacE/GsVnKfU3R3h+uKsO/SdvOoLhf2ddm2UfvGeAlK0YXlC5YuRlf7jLsjwGAGKYyL7hDtz9eRTzlxUi2IyJo32dz6Eip6vOdX5Pic0pJ1CoHDJ40yKZWXlCAze3sEe53oaqpTPOU2WOniZTCu65YAm2uk+lEEQ7hNCL0GCOLIrO1wdZDEYrarg/z9rrbST6srZmkinul8JTFX/H2uM4NflgYmwJ9oYaCOmqWmCxQpiHssNbnJNXyEfnn1TrPdYu7rnf/xnR/3Gbyb0sbJrTx2m/VS8FyAg7sxHeWGNAVzHrSA8njPuxVkYq510f8U4E2RBIM7xl7rTM0KVQYkcUf0Gr64gHCinwhS08Otgk6PCkBJb3QnkGwAbUkZ4iNJrXPaBuwqZKVCW3vWDpMVFLH3mNSfBOaO5QD7wEXFc7NtgMsOqCU/6NkJiFAGP/z

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: game-data-platform.ru
  use_tls: true
  argocdServiceName: argocd-server
