deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: latest
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    GOOGLE:
      PASSWORD: AgDhgp3JVJIomUt8hfU79FX5+3tK13YOkC3E8cmLd9tGPvrvcK2h5yylCHfTRGV1m55l3sWlb8van+Zft3KLXOuxGu5hli2kUoFuI9CBgdI6+Lrp1aogx8OxRWL3EYdRVnl9j9Y9LnWTW/fPmNC7zO0vPqTibyKODn9t8K+l3QCveJBBJGBMPQ2/AFJfdiylHlDaj7+tn/Ohz2G02CyAF6AdkZ9Sr0/6m4u2yx1a+r94DcS18e5uoPJV2RgW6C3ndS8r0qbqYuSvVLp5qDfhsZVoGRaxGs09uYnVrwB74NVYwX21g21BgeBqb0+KvcBXfbJxGE9yPmwKi4oWBft/tu+bT1JUWDjq67o4Khjjim3Rox1nYGfmenfu5aONqC/7R2zeBc3QIm5oGalrgFyFzUnkS3HrPvs3Zu1o0QiNaTgaA3fgssLVRL5vzKZuDP6W5vUZrBFg1opZg5lliyB1blr46nnuwe+kgAr8Q9sK12Ej+yo2pgLyptzAT6K/qxtmwlkPTqsof0ngrBDx5N843GPDbRiGYW1Du4DDuMfXDcqMAkkVpimLDTdq9/ykh6p7OvaZWPcsPD+AjtOvmWN9L5BAKUJjkJPPHAhwy+yhFUX/eyCDGfo+XEl38aid4O3zUcRmUvnqH9jPAWvxbU80UI0daYchMX7snzsbbPtr6+NgQkQv5MSy92zeqBaeahFlIgtqVp2k
      LOGIN: AgDJRajHmyh+MsXOKdAMsUf3jWetH7fioOnMdWgWC5U4c5UqKet+k5NI/RmaUTC3MLEOEiESqwjraxNh+5qJHLtEX7e8EWtBS+ljAS1dql6uV4cxIIloU9PIH3E3ldYO9ySiFoFal5YG0xETfWNIWrRB+1AqWm+0m/o6jU3UZAGV1w+r4ph0UJV9vRLt80XCD0vz7LCu4VJ/lBXDDAXYZ2zBu7Ue5t8v4UhubER4aR0R3UkwJFT55nyr0pqJkrB7jBifS7kz8CEklkNdQh9DKp16cHnEf/AMDHWsGLR+H/Z7lHuuJhbdIK7NWY6v0WvLgDmw1sDZEd/3X7Idx9Cs17JxcxjjytfSllKdd7QkULNDJo939HyB7tYX/LQbjgOmUScrdslZ8v6Su8hUMm/NoZEveAAIqAnRbW15uUy+0qj9RvunY7zjF3aDO3O1GwaqEZNGaLU3JD6D6QAX5hfkpF6k6rqYP7f9Umnc8i/HHb1wN3y16jyYD83JuB9B7ObpCfAGlCQDnd2CmOioTkQgOihgzTmtFhNqFWLaYO0xoKsb2zOio7G4Me+hjI2uGgTNcZ7tDmT+7jGF3UObrjDfngN0rnlTFAVqJp6D4UwbYZS7WlV6pd+yrHHTDNHXg46AVPw+cQpmJSj4bAEUuRYuPscCkJMJEReCAT6TbA9KTmmYRGzyQ8DIP2M15RUwK5zGyqWA4KlQ
    HDFS:
      HOST: AgDElHT5vsrVgHdQtjnO60skO40MwZOlrQokFbklk/ttb/5PaXdbOAuSvdlHqSsmm2Li63W+29SgPkbdsh8Pm+SraftAFeBp4UpE0uoMnqk1G+u1e2GEw+XBvVPuLHo9tDVt5CtG+IlpCNTl2kCpTcPqDi5mW0oVTycKjW7xNb45iWt6qjtYSV15DB/JMiSmW36KR/449kuuMuFp5xOyTU//D/rt0AMWG0N4wZePPuYaCTmQC9LDh7lA/XOY5B2Q8iD5oyNb3Mrqy7HqSqsYmgRdtZ21XVOyfdySSWr+L5jMmUDxXHMOJRMD/sugJoPC9qQJDYcEEM9JGs565iK+scvwK8mDFtXNkgZGuYjI0upz5E3mxfQXtygXZOTpQnBjXWT9u11EZZ79/lkam45f3ncXlEwgZfraTvIYoGREX+Uc/Vw62Uc/5DhMTXilEr+AeF3P2H41wMZwLTjsZ5pQPYVtlofH4FsGcf3qQy0n6O48Cr+4yJQ5FPIxjOMxmV5fEYKphIFObJnbThz7PQhW5U1yayrsIVLAQerjCPfadFrs5mBtHpqzD948j85Qz9Y9PXzO0ELhm80fjZ6lWl8bGQNq5rb94zfDTF2e7ulTm3pehlo46TG5bQi+1uZhTkf4IHHQ6bX5Ep8ib8z2CFLmR0RTKouo3BDiPXp8XJpLxin4UNtZJf++t5F0oFfPZGXQemYb0JULpou37wM25VI=
  SUPERSET:
    GREENPLUM:
      PASSWORD: AgDITc4xTwTydp4e02YZzdSO27/c8uo7ic5SlojxuCRpg1K9xQdq6XO8dOhnM7le4eUW7Z2u9mNPb8vwfKqqwsp63eV3hRS3bZh/RxwGhUPbEVTzIficEDk2uFlwAGmpzQIms3mS8Vvee+E26WD6kUYwUmf5FtK2ZzgK9dvYJ+IcObgw+QJNvAGCP5x7uNnqnM8KKZTEUHiD05dm0L+AufdJVo31g7X44gm21gLdaaspsaCubcwUQ1noNH0pr3hiaVOI20yY93c19tFtPHiWDX+rN+M/cSe8r+OI3ZEUOBAWbfrRvaI3EGQaPT+WEco9PALBTlVdrLw/ypXcgM3tjThdrxM0RGZjx7u8lFIE8POXhW+amURvXCiWGi+HVP1FnrFoJZFuhYqHZWCMKvALlk0d45/vGw7Vri5H74uigokUCpzMYHbUnhUlKha1MDREbPDnDHISo6+MBNPDzp/XxJzshWR8JbcRx4MTkYoVG14SlJwZomrzKmNgfU1qFWMLSG1nKQYlSQ7ipQuVMsy+KsvBPjIh4behUPVHdAXo7MmkYTLL6xIK1PhFy3IfP5prIFFR+Fob3xnOg0rjZ1RehHsjDvbJ1SDy7J7H/8p9tjsG/O2J94ddM5lWPNCFFWFnbssBeHFAe+vjOOhjpAu6omGDKJC5Sfmfbn8GNhkxJ8/msMgkr4kW/LgLLy9sR6fbn9SFcj+4

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: game-data-platform.ru
  use_tls: true
  argocdServiceName: argocd-server
