deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: Always
  tag: session
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'
  flink-conf.yaml: 'slot.request.timeout: 10 min


    '

namespace: default

command: null

defaultTaskManager:
  memory: 1g
  cpu: 1

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

applicationMode:
  jarURI: null
  parallelism: null
  upgradeMode: null
  state: null

tolerations: []

secrets:
  FLINK:
    CLICKHOUSE:
      PASSWORD: AgDGPy3babWO4wJaGH/d4dxecC8iO+ptI4xIzbWsC4OTft7sxBytetoPFNVwo5NNwYh2W81bxR3vzk2S1O390fXAISAVIEcWmFxRJtqJaVM7RyuHK8/pr92DXK9dQhEGlNPhZ3rP7Ot6iYfbzUPDXchaXxE3Tj7k99nPmEo+zrVmSL+AlmEUi/OYXhS6NcvDCDsJW04SL3lwpDN1o+/ebDsbnvfVnouLCfrrMD0fCOchJVaQHxiIGzg6nUpygen8HWxunVRzyaSEuUAHoq3//pPoRylHDihz1TkZCH5dgZQwwD3dkiStD2pSNd/mlj8FBDSE9NSHiiUF07gMI1QYe5zgHUgOIXs3TCIbj+RLdZbwK01RN2nLX0tJLV8umyMf6AawPbikBR7i/sGlz5ogv5btnlIWe4GUEPeTBw08w0oUapXuj7656L1nyngtK8Sn7XuviTw3uOPezj0QrjexZodhcZi1ob4p/ZV3gOEj7yWTCYEmq88VR2MdLQfPT0At9wsom49rj+7ApsWBk8rybjtVhBg7A0Vwp+NtMC1GIap5O+XPdFzdB2OFuXwHeK4vgQTkwIA0gMnavcsRuP5h9gnoxQmbC9sg6UwY3ixWx+jYVq7pS3N0/rj3ABDjlme+P1d1oOxvqg8a5Qx5hkAgLUd58Z+4rAcIaP8S2nSVgyjKimRY0KWNV2Xtg4wFA/wsiHUgenw=
      LOGIN: AgB8fsR/ysOXGySB0VKwb/P/obab46gC+pbqgRo4Q1598DjHjPPXpzeLUgvIr28wZ5HKoMUYyI5giAo60813uS7fCUt69JeYXL1FW/Aef9KAwxW0IIdSCcpzjDn0oS4YvZ716PQ+B//oDpj/HUHkyHM/Zhytn96q/bdekRITN4fG/j70NAxBCIGb911c58952W+HOZ4fnXYrez3/d0sPO6sT+EACoYv9xnZ4ziydFwj7q55SohPtvmKLc0S5jKmOk/zQ9GVFf0IO7pw4HWY/eBEqw6X+HgBJcgmGF+gzf+HO3/gHwcja0MjoLwissFyffW0eaNzWnRnBsDkLT5ByLsOpzpHJtzOcjryWIChOvYAOzi+dWk3TPL0R+4qdIGuEcTrBKcEnH6ha8Gs7SerOSYqsXJBtVSBYpthkZ2rtrIwOg3ePvqXzEsdCPppKuL0NCmNYwn32RYq56qta2O7u/3JMKNkxmYbz1ZXs/lbLD/+OiVW5uyNdourYo6xtIjYFmZZfYKEnNVYnMk1nJVmsdv4wNcIRawafHFX/C+BcEAadT6gWh7joF3XZfnt0BcYOblYenQnR3x7tk7P55LS++0i9IUCmLucme/r3cSVXb/wpzXTgfsQ8FViLxuX6tsJvajasRZtXeeA706+FzVbidq6PJ4UPGXr3YeMpZtAo3NlpilcgjeQv6t1VPkGHrNdoQNL5vcCFb43kTjU=
      HOSTS: AgBzuXHEj89WOKGkCwN0YwhjdmXE07EJjjsKZ+0U8rbJEf7Z8dFCfA0yvs4u9YTbaL/jyLyuo3becNuogwGbDpEesd+eWb/5rRJQE4zdIw4rlmHXUmd/VNQ/BUKa4yOUYpL2dUPYZlSXJlNw7YvRJ6M94UJDHRIVYBMnMcsA9FcSPZyKptLNoiDgnPUtC1cmWhSBGlAo1SYkgJ1IQpQTUexb+s8Waw3AmfuO3KRfVFIQOJUvR2mFqI5snp5i6M+10+QucTBmt4Hc1noaLgII6jWesGi++6/+pDEfIDNNRZCiJfKobAOVppY/0CaZDck8c30lJdRR6zto3rXN2O7aQncnifah4uRdDU3cTgMYzBBcABQ/9T+GKAynfz6z4EKkyF/g2ESDDXHQ9lDwikzcsAzCXnkO/4QGOsWNXfJbp9LwS6w/BpjzNnt2XC7zBmmNCZ7d+6AkwfY4vxt75m8PjbubcUFVTCDoMTxvgB0xmwvxxt8+MOuS74ytN+2OplymeT4xcWfIn7bmeSZXPOCc2LYW4h2fdgCkYaLy/uXiE9aaNvGmW0HojNdDTkyBjd0SZEBz1s6qmQzrtxCtII939WSgGjzVr076TtUaYAnPGxOZzG20XhEikSo8IH0Yby/9+tBkC6ZgT3ECOZ544CNG5prazAz4GwlsH796H71P8Dfqeuu/WSvTM0OXW/gn5QmV7GU+MYPPvc1UVLkZmdYLgo8DKDbxD7jeH55FcL2WVq+7xflrUiXOeq25n8Pgu88=
    KAFKA:
      PASSWORD: AgACuUM8UJkQHh5tWG8e/nTzab3n07Xl43DQaU3J5IjJ5R9nYi0cLMw3My+IN/ZiJl4jQIMK6JswJROkh0b73QK4DAUherkVUKdCNWZcUP8rNhd0oW/5pK+V1BYetThs9hmVMuOqrQk3p0y5bVzZweFhXg9GwbMTxHs39N9NIxK+mpTg1X7RCnhlNJ+rOKmr4WqzDA5tVDKOQMTVFebReOxFLfRwlgnRZS1Vq2NcJFd9N7/1OEVIAaUM4+fnEjSV/s/F8w09icCIlPAURWTTlOjdjtuHgTU7KmS7yhGv8u/IQTdHY7GWAnkitBjDwD9UaAft+hsP3dyuDc520yy3QoXsJXHosXU0kt/iMq60sQqCZUbn12EpvNoZnaLNLKS1r7cLzSR8vpbNv4yzElM6hK80iYl3EGKU51Zyx4ivE29NM5ToCBTSanXnnuDy2oQOfnPPdsnxdFQWafDCJjNcb8r0lLSXI3ENOtHfwgwC9cgZEy6hd362Eg4JKKWRjKscN42j89KdyssDnH4I2f3ikIsFlVWNbamx/EmPi7UMFhvBNjgx6sJF2fsFZco0quNhaCyJEQ/OXRAvnhF3++PUXV1Ifp6APJKDv8ZDlMUdUxsQRUrfEkcXTsvx7LyfAkNybtyuKNvgIgGeVJS6pkwpeqR7HcMekHqEggnNWoW/bP/o8GOnWHu5SbZT53PjZeNO8vGJzI9c+OS7FQ==
      LOGIN: AgB/ucUhWqVxsSc2TFTy9mYq5o4gz0knzn1jIdY8UvTJqlmLRH2JOH8C4gDBnhXtaHSdYEF76uFjsSYqfzYMXHNifxpb7looIVY/z2VSHRM4H7KjjX4lZej5DiD65qM8aT7axmHdh4ZK37kLTwQyaHoWSfAuD1F6t7xExHjk6r+4cP/nimXa01bmNWcPduVq8fNoZFByZLdqqDjPju9dXa6kUueH/OJ2OWte920tigtTXRLRIMxlGnKDAHXtJ5nxCIt8elq/cgiUquDBuCf0qwukceQKp6NUPVlD81BsKXP6gRNKNO4ICNHbkAzWBPp1m0nR8+y2MC8d0hJh+C12bovQtppfbfp5MQMJHaG6bj0cm76ZkZnInr6L7l3c37skXftg6aVuAS+bt9h4nch91W4UrTuVPkDZWBoxay7pqTC6+ST+UFyrKi3rD69UxjB4Loay5nnUN6Z6mPMZZyyD7lIXyUt0i+K/LLVxJwa9TQGjVztZrqM8vApwvCEXpxv4a0GCD00bf54xFl9X1NzVyf5zaYtkkC0DozWEyOnOQBM9tPnpXEiaP82U0Hj8nPSxNWbSSX9k1gePv7NAuk/D9H+AbjbnITan2tuqNznXZuNgW8Ts+etCiGx984iWWi+3pnemt9IrTqBduKvJkRoHbLKslfNN5PqmdPehEaMEBUhOvP6S7+QXeQUnwsD9mDdnSOZHDSIa3xj/anc=
      HOSTS: AgCWadgXbfHSknJ2ukoXyDCvWdCxVxd+oV1OGh1N2uHvKYp/pOJ5oOr4dq/xGxdDOzx8y+ah5nJqyIcVgeupclQZ6BSpV+xYlcojim7ullSS+bsclTakCPp3qLJT2RrXrgngWU8hvulYFWXtnxpNFBqHzHIuYcv3fhUHlvIICsJo64R0sjWMkzvbnniimWvbukB4Gj735ba5kjeXa9suQpAQxkKubbQQmDpNlJeQerc6MvPm8dpz/3GNlEtBI77D8BNdUgR9bffwT/SEMRmKdUcg4b2DebMyeOxhOTre+V5YmmlPlQ6pZmCURWMLZQGBlYO1uPZDehNoolPskN3ot2rMzlK2Us9ctPcpDijBvuLDrqTQlYYBK7a2dldses8KCt5th9QMCeoov65OQc7Lf0XrZ6b7SjCESLCdeeSzS2kfTzh5iwokb18qs0uv9X6iXDnJZVeyAd/jGDeKQBcS97hbjfC4bWRRX7cTNnLXObsjLcKLnCVpshzLkUz/Rv7O67ntxM6AnAx5ahiQ8xyqR77sQQjmy3SmhMnoE0WPmAv75m4rbAOTETAa24nP6h7Fo4T1DDHKRCI27oXeDfINbyc2mB4l08D3dBwD4uhuTDfMK6oKer8/2WBU3UA84/y3oy3KuSavvoF4Ksy7zDIkHzP1V3VqdfhSIeHValht30gIX/ozAhPJ52C3mTpsdaYzOrWWn0+AI8LIdbCcP1NsGArAMSLAPK3QEmBWwHorQXxZ2+tUfFN7863M6wQsXr2/DWuR068dWom5xFbh4h0soXPQ
    GOOGLE:
      PASSWORD: AgDdZlDQ1zr/Lnyu91PCAEQRqa5sYddotw4MAhQ/wZc+l6Kb+4OH1ajfZVLZDAjzNYcfneyKum9jZ/LIk5RmO3zslvPTvBHsscpg7d9luu5f1+/x/VI79bvdzAZklbdJ0Hy2/IeQqJyA4EPKfXCEvn3VA8nrMXjCEFMt3911TnByymMkfObQvYqUIKkW/yOkOpnnjkR64j2Av67U0DShdRERjIMAyRhurnyGDzDYNqe9t4ZSZsTRw3xpQsF0wH5ZrxDopIrdISDCGKmHC36tAzL2e1xnGjInIrSB2w/U2FMKY6r52lvlsLwco+ocEXOe0g8t56CjmSltJ764lwNJ0xvztxQGXCBRCOlKoS8Vx49Hc4+DDIscMc5acsfzs4/oJtuW3ZwgHL1RwhscCvzO9LiV8EEkLgpMsxOEZA+6/SIX9B98y1YHclhbo522wM3zv/dzk3r5TD/A/5lNGEtvEB81XNWAF4cVKq3sc28wb7HXYkxcOf98O3RMFdE/sUA55Fcb8ByHoPtMWItbHFJxzKJxcWAQfnlaGkIal/SN8fTpx6ufBry5NGK+glCN7FC745N3x/l2OjSrgUl3WpTZL30GC9EcIgAJDxQhgAsm2RGUGCJJPhUo8Yn8A6r2ffwmCvG/V2g7+koKTe+Cp8PCLKj0AbcHWEg5C7ezdk0z2+d3wwCKSH1PejYmcButsJEFdjhu6LFM
      LOGIN: AgAJfhcIyTMYnTB2lfNsvWP+NlXATAHfnp8WbtEWsIRd7v5WU5i5V8XgxQaWEpiv2/I8l1gaQDqIZu274OU49qXVedpb3BqaVR9z43YJj+j8Q9oO07aXKslGqfSugqDCLH0/5MQfAmD92Q6yWxS1suozULgW+YptNkjLSCvqmuNp6NtQ34dMrSkExOHmUirPg/TmJAXzUj5+JjZ2tgts3aLZpENUBLeyY5TXmHKAiOQRHm11mwI8nOlCzvcxWk8VgAbq+D1CYu/cuTdJFnwEONQNJnN0eveF7feHc7F0nUhwQsbCC6aylarlqhdCLFct8plcxdTt2KX7Y4awtTsipPiOPRQ21AJ9OEpRG7748XbiaxUgmTDEoWeJUWiRjSC7dasghuldEEd1FKOWVsNF/lLXGKUBP4e07/VdQe9cvFbFXxpMAVnV/cvLll2CReD8Og6sZECImOyfJTbz7FAkTH+KfZMaBzhtuMbSug/MiZa9xhIqcX+n8jFVimsOImnTcgseAG9AlW5YssV7FtPiT2JjG29+dF4jjqT6m8dUvykJ5gl5bEfbMS5pp/mwfgGxaV48dAxLjUawiueeiUYDYUw433c2OlpaQLXrnxkcA/cGF35A54NxnSfqDhaWOms9Cjetouv8zBWVL5sTXP91ajfIcFwmlYa6phU0roiadKT4ytcAkWj5F1ASGiVXOmzb8Jxvnk0c
    HDFS:
      HOST: AgDMVlK6k0Y9F72nTBN7oan6a/lSKjVyS9PB8zmiOxnHHOf4K4h5IpiynFKPAqgRLQBqbWzbiKnDCnBh8GVeCEhCZKkNe6ZthfXgKhNjoDqhewRRNzPolIiJv3psHiU2qWSpd2ItGXir52nDsXrCnugW4wdSfviTBit0WZUt5Op9tKLgywy41FFiC49/kw3PlIw3F8XwCz39jTdMaNxa1YY8jV7C/fitZxyoBNYiQAnorEShrl5JSj7htgK/s1LJGLFziKcXhPdOHHvsDENuXAhp0ES+3VbgTncwIBt2xZwo1Hgiu7TDJzKugU4ErQrpvK6LBxDo3IvepsUbIwLZ39yIfCeF4uVoGyLEkpzMnf5fZzFoqC3GsSBdNeW2/PWpK8qb8qWEXFyiTdy8sm9/Pj9cSa/x81d59mBH4uS0wyRNf/LqxigXMW3bkW97rAkAAFMpt45PegIep3wKz/oFqMC9I9Ep3eECl6ZeRENvGjWQU11F3fS9sN/0YKGkz733cLVlS5zKLh1VOgiU9+z1WyPVDwYm8EwIzU5B1WZjT4vazD6nMCdiSBzFGSVuxNx5j7RpE0NKhe+Cmkv5xShCiK6sy1vjxikhO63CWd+Sy4P/JWJt7sWdoAuXPYulf0+o2ESTghQllkKSwpyzUK7vCZM/X8WvyVLv7PpMweZrwVK4rKP81K5U1oyVO1PMIaZ5nNRmJ239dyN/soqm2Qg=
  SUPERSET:
    GREENPLUM:
      PASSWORD: AgAgJy57sKgjO8PDWEtps04wZPAG2LEiZkfGaSsP27qkcyJgkqEfY/d6WpJ9D7NEfvBpR3sK+O2E+7qyP/27oQYRKD0san2Rl9fvxnn2/2/UfY2oP674bPA4//n1UEVCxIKsubc5/mTyDMCOJb7oFTGoqLIhwq1cXv/NyZSKPZkQ6UIJW8ZFwzWZjeKckCqWz+by09emhb57IbwCjoV7PKGAcgVjmXF/vzBrg1eAbhXbK+2cnVASMwcSF/8ZCZ5G1c+/tE5FMijBOnP0L/S11Np45awA0Et7WfDzHLduJcbWm20ilV/qRHmRHqVJV0+KERgp0cTEIk3A5Y9g0cvGTStivD1GySpgVDlwVroKY6R6uMz5c4NxOrj8fKdEbqVV+sxcx8IT1mmFpbJrM05hNtTfeT6FpoXmNNnawyKOPYr4u3jv8UFAWpaRqlgpKMbgB0kbgaPxcY8b+RdVI6Vk0fIV0YpAXIu94ctCC3AgIZv8L8h9uRU7s2IR3GxYLD3V8b8QAzV3cF+qOyOPf2ZZrk2Jj5XiWBOhv0TjlooGthUSwmAM9sis42BCw1AAfYNr++bhKjZnHDzXtMpzqo4tyZs4HiLdOVBgMZhED/erYNqKBv2IcA2Ux1Jntda2onf/KDG1Zd300XumaJT7b8ZVKB8M/cTHkygoWsMnSTVe6Kf1BUxZiU6w87u9gj+LuSwaGHnTOUbY

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: true

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: game-data-platformm.ru
  use_tls: true
  argocdServiceName: argocd-server
