deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    GOOGLE:
      PASSWORD: AgAF1PQHx0a2tAgKwrzF8M/+xiUpxyva55Vd2zd/9/T+bFKPo0/93iZUFrdhfoQTVAP2KSu23fQb5kSc9VY07E5dl3+auwyk5PzOdm94GuO8sdUyN4zUih2ZucdM3gX10t/5ZflHttQVX+e7GqjZFSkNxvdUfOb8FrjwUdvoayF50blfJtEVLIgnBTc64Mw8TA8G7+dQfTAyRmfNEYDn841srQI18Vf0Rdxx6GX7UX1VGkOQSz55p2EjzIrJgiXeCoXNNQ/xWCUVhiut6eGVTr3h+7FyGZpALCTHNhZrj+cwsLI1KR6VOs1R8NVM8UGOiZbn8L+dHfmUd1C51un0nMCy46ngID+qPz8uYTd6Hceml4MBGBrA1X/k6c8zIEs//gml7GdarKxMeJ6HjhEjKnDQhJwCrhy/86t9Skf2/vHwiFgj4ecEUqI73Pvqo3D/SPTgNDgAfLZB//lNhlHEhwmjNm4F86tQTxymVsl7+DQtDhMGWHpQF+fBaZs0576DM5+WZYtlfpVQd2JGmfw8ORqFtDTbAIYH26hN7A0sR3mtv6UWTsZ5TbcHMaPO483WNSE/TZooF4fFuRnWEdqA0Lq9YQq5lxpoua4FNPBcCMZ5OPO6NQGxxdkOGrNh9h+kNJ5PlsHBVUbQZ3fBMHsfwHhd1hKZ78mJUmoMs4l1qjUTuUZxqW7vPbKZEyaOXO/oVNTf/qxj
      LOGIN: AgC+qbMTfBOJAiGo8jPazUeu0IYThELwTFCwKnQzJLwPdcd8/C9WsqI7Gz4Dt4RLrhDLNdam8VeXyzqnnlrFO5UsTrNm+CYF9kCFN+jjOowgR7Oroz46Is1+l7n391vj3lH4aypd1+F8ljVh8KeHYpzSQU5ztJY8t3HTE0cWkauqQ1SaH90dYchsMtLG3gQqqJo9PCSZn9nhE8emwxKkYKxtaH4E89HgZ6blVI8EzZ33GVPVD1L3TrQPamZc5MNHxKAbu7wIbTKSIcvURPctbTxXu3HV71vBWQ43ZeWldJPS8eI/WyNSgD5OhnrqC7/EPVkeEzwhNKTmXS1rg5kb/XaQknVv0DoM6UqycdFDQl4ly+eafrw+C4UDRIjVTpU8I9Wa5vJQEEHFHyeNsJE8UMWNFwwF/KLCWMZmdnhFwbgUtieFUIgglKiZAaCDD+eJ2GfrytVHzgDngxxPYsMUsmDsoHkz4hf/WHgeXGf1ovun4vnuuN2MAj8lezpm1X1ok3zUIZ3uCH7FCc/L76mxCEhxz3Htjoho+4cCdeL0Ss9rJ5gYZkJJMAJmkehMZOpcFeCc5LOPvAfCrBK/Xq0LzwCzHkHFxc/070pFal0Hrxx6h1hXX+q4MAf3zQTaEXboDMUxEcn2ruWW7WSvn7p87DxK/d6q9LZjnH2M4NCYcssKOjfLpSoG6GDgmRHMv4YlthgkA1m/
    HDFS:
      HOST: AgAGNG1C8ugmkLpMeTfG7jAxCbf5h9kbJhmkgxl8pimpHTKhcBfBzkeMknHk99HrVBosLQKIohel32u94Z1Cp9VvHHJSaRU/vD7qkwzL3DQfzZXP3/2Benla9Wh3oCPrZUZ3k01Ucec1aU5xLhHgorQVPva3LE/DiiEVAbbsHTOEO9HbnqIdWzPZ5Rtz53PkP3dxulId/hDsHNoEqWSoZVFKwrNuOELsP+1gOzt/3MUF8CIgC94fX6662DtqWwiPtLj2QgHVYl3A5Li8+tHYT/d8+nsS7+liyXsMFR4x+dzxKgyUgLy8hTIyHmYcLeClqRkYQ31fbatCUH5UKERnmn9vFqeWSSDU3Lodv/yKQQ09Duj1wNSRFkpaJoiF2W1nZ2t4TjHKa1T6dkdnGHpKGs/RydUt4bqpLMU2RziLwyHhFm5ym/YhbvsZyj56cAiAvi0KWumzUYCf6Yfpy0L8N2ZLreejeWpclZH4fstDqc6+wgmRB16RT4MXTZd/L7QpEiVTfQIVffgnFJXiqShlxd7pDSC+4QOlt6BnaAyPAvokqPZycx2H/OgUZYwXV6j0nr7N2c1Ipjtc56AEHPr51pODE6rgnbrrobwJxMZPj7Xo0XGQ9UEabpXRxbn/KyNMmfrAhnbsb6FhZHgvzXuqvISGEpU09+I+FrLR6rngTCpOLOhIHhWBo5mBzMQs9urpBJSF4qQBuO3mEppfGeE=
  SUPERSET:
    GREENPLUM:
      PASSWORD: AgCyjYOCO5rNsj345+kq8XtAypeMnKLrbWIK9X5WFvSsryH4h7uU8oUd6I/koNk3inQH40LIhjUhWs28rrpSalWMeM3tsMWHnULGcFOrVRz7HXGS5O4yiDqVMvLmpFAkguGyMmtjS+A+Otfr1Ap4+uYvPDuDDzDTSqWVPQIdJ13luOkG6igqEf7HSnC00glQR4GYvhckZCfRB+OE3ac9cpeyOgdK6CvgFFFD7CpZa2FmWdNW/3BcM8a1+ZlHqC58E7Oa9ms4IJFHt4+8GVScK3mUkUtSy7JwxM6Po1bY3qPR/dHRnunQMYFPLfZA3jHJj+iyfFcpYEQ+Md0UWHYLGzJvFp7od6rr5iUFOn1/LQzzbfQfMiIvp+QfF9rDLwY4MWXnu87Ea8SE9sszvjLvf+wfutwbTNHIZxV0gYbmsFss/LtmA0VDUjx5uWbR/FLFnHCYtJ2op/agjSEnwPGG1GYmWzo0QY3pVPbxpUUf10zgfRK8LKYSBpsl+/WcTrEYTrwDkgkTzV4DD1Ag0f9jCWuvQv5JeBy4IuMF/Wm8o1HQt4oVSALqqAHm9AXpFKG9MP5LvlbWPfPX24RYtMA9i9ZOe7DPsS1G9sehow1RH4LMoJgxADXwntwxMQ/gcnLemLkU/FnIFqmv0lhoePG+InWUcsPMv+LeR8uaVunha+Q9wGxP8CRsZ4PKyS3qGerFOadgS8by

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: game-data-platform.ru
  use_tls: true
  argocdServiceName: argocd-server
