deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: NodePort
  kubernetes.rest-service.exposed.node-port-address-type: ExternalIP
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgBUARh6yecTAJNuddVyXBg8zWrPr1bng9r/d54E/H3+yksJ0wAWs2kXG463mhKjMyWwNXcr/fHSYqltfs3v74N/Vj543XTyWHI6MBIgct4O5CQUZk+CA8VU9l1qPqey0qFHxRLmVVb6zfFATPR0lkJbjlBOK6eHA/Czcirtrmnj9GX7H0sOqIrbXGf9sPSLm30clsXBfVlG8KIu+wb42F+U1bHlTXSnsm9yPWZhWkzbuzQ/oKn/dnNsmmydtg3Izxnm5Q3reJ8dRMATBv97j0fTPdjbS9cowNdhWtKx2lsUK4TgURmu3z53e4fuBcjMVCzXnbe2/+cv6SMyuig/mpGfaEIGa9EadQv01pqGIBY33bbqqTVkqlSb9RlIlnsgxkQJDgXbhsc88yTWJlnMBEe+mQmxA1j+LicMFOIXslpUVDDdVlGsEp79H2qIhWJpn8eZaaErlL7N+4mzc5a3br95v/qnmmBD3UZqM2OaY5gJu0BsHxcphOdEXbonosb9rWVZqHOdTyAonBSGOoDpZY0u4hPBsZiPGK/dOLQ8y+4GSTdORKqJXPMmD1G8WN+JZPAdnZZXZXY+xjDPkeNLbKcXiq4AX/YOog8F4PwsZgFQk2+wHbq5JG03Sf/gbTWtyVQHw9LM+SViertw9oEc1luVcLpsPcNxpZvMpkYcZ4Bx61OYsSVfzY/H3vvWhIvRHwbH8uBhBw==
    CLICKHOUSE:
      PASSWORD: AgCc4vTnmIPKiGlmHNBo0G23i0Kgm8B1SeJ7wwweuqXDLKdgRUNrryUcdWHlvpNp5jUqPA5fvYXPJqT3eh1P78OMTTWQYzrDvmshDJJxF8NjYc/J2xQOdJoRe2zYCk+1eQUNSRkfKqzqUaWwCwrQewOK0CBFcmKM8U4LTjVgPBVBGpUMhcRUwJSgnk/Ll0YbL3/r4a5IFqmLCFBfPpla0YLRczqfTxVpF9hQm1/bA763na8Dzb/X/XN2qk7djnd2Ob4z1bdTqzakFxZBz9MFxWxgyiSDKLl/pBW6nU9dv82/Sh8OfWaqZdFrQKqzKnptxxHveKs2U725P9as/PG6ifIl4VmTzeSiAwXRm9xazmUo3AJ9jEUmmG3enfmtc0Kl2eJqtawYdKN9M/gTXYkpOGtlZtlY690iBQhe1BGt9+UKKeuEL9Q9NSTOi6VDct+UKzssAyOabktQWQAxRatKGNw3lq1Z2SQE+ySBSdOZCISgauLmKvOLAelRH6sFl8m63CcNA8lHYmWEZTE+zxYWEjOC0TgGOvendflk8o+hKrGVsnjK5XbS7yrLoQMw6BbqYFQSh3N3UVZUZf3aKL8/DcVRIbi4IDdDYrKfUxjff/2GzHRwkLRJIsFQvYtstsiDAZ+24lkWLXTp7mKNPUVByTHpnUOITbGUfWyKQvz0ryvw6Aq0uj7sCp5Basv+lJtdog94WHN/hA==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgBwJ6f/oXSF8n9spXpECFypsG83bjpBOiWqnnfLmxquDMYEbP6XOm4uNcpRg+gxLxH39FQz/p8dxieRab8DPpQA33d00lmCmh1VG/r4OAX3y2rrMw0o4EEUDJqgNfLv/hdB7AvrBcLw0cpsm/4HRc9OutGUMsCBJGMf5L0ImbzFBkuYUcx4leHHRKim62T1/UHeq7RiYBkSb/+0uj48yWwogvuzsmiQQio9YWjg70Paa/puafOdoeNzYwQ++jmAtcqzkE3qbR1GQ/e6IEh0i7hq0+FBLVToataf7mga2t2SjCwk66tAuqT+yqS/x5FQnKkC/QUNxGabIsNEicGgFJKp2u3PIoXKNpXkBbrRaQA2dkcrrBnB2OmY8fQnGeKxLW1540GOcwXQzAw4G7E9ddeOI9hWzG0/icgTZa0fpgdcV6z9R5DIeegcyGwTDZD39JV6DTQiUjAw4zF8vDjg9kcLUqlU8xdO48TVPPzWkvxlBNMnGaQ481Sug4WpRoI2qV7O7uDiKFBBDK80jdZDYCz88yFYwgot7MOKeG+QsfQ4sqD4IOUMv1nbU55LgFHFxKes1Qwp6OwJnXWJG90YGczFgagxuPgb/JdVB8+34KiMQ27TTo9FxCowQtIxM1hs/WeC3TMRRFX9bmy0HrSdQujug8EnRd3IzeNZOAty4MOL7TBHApraq5TNOagDrOxAeuv/5EvZqQ==
    POSTGRES:
      PASSWORD: AgCrDEp7+Y4hfmrEleI14cT4prMMmcuLjzLw+6QjWh+SpxRRkdRYIAIQ4sfbScg3VQ2SNo3emNVk6t0bF+ATdm9cRd6mjQTRSzHs5FNbbUBrufb00cu097p63ChakhR1T6ZlMlxNBRE0vp+plUxJA1F+pnikFxxZ6HZv+PH5ItURyQuXV1IZA4VAEw/xUvikb958uePEl1Tm/2mBltaiYXdzbXIuN9I4m877jyCcx51KUaxGiJxWD0Dm5jzXaGsIVyvkwtTzDgz/0obVFvRy4YtvVadt/fVMqhc0VXBy1fRwI1X2S1bgLWapA8RVnBXWkYmHPcCeb3Z8upPzZMeUn95GXxCAdDA62SwfYJBcEAxQSSQwwsf4z5NDb+Dr5cDxRjS7qdGMM+GlMHdF9fPMZ2NCY8PL5zSyRnZcQoVbqCILGDoOB3LkvNCbdU/G2pn2X8PqmXyDxLW1PkUxpvoOf8fgMz2nVwKBf/O6hR8j3gqMEjvK4wIYD52udvWYKEDWgw7Gqa6d56uMs7cmFaoAespW/FjqCSf8NQQWWg+tk0itskIzVJZSGptUHswI22sMae5RBOqSBl9yKwLpPe9bpdly7IvMBqeJkIzolOkF4SZJfoK0K2g0b+Qc7AdTWqBs27IH1FJ0x4NWfmEIBP6tAo1e2xwMuzbaFXrqbFbj9Judz1eGmeNLv+C51JsvUf16VzmheuJBrg==
      POSTGRES__PASSWORD: AgAF4LkqaI7WfMmG3FCwderDuVEwd3gwFLMy3vws5rueN8NRiqKEa9HjDxjy0WKudVEOipive6neJQnAmvGYjRqZDyO7eAIv3XarRlxGbAenQogMsoAnYefWwJt42yUfcaTUnDiqOsWTYyl1yM9CmRuK/vUMJb2IZ5DCsHg/nHE5julW3fUJ/UMfGoswFFU+WJm27pjUk1hQL87KdcelEaWX+AaNVKJfqwbu2cxdj/sPKATjP4zXTshjBARqz4oiMx4olqK+Hm0nqSLCS2jDTkySspi7osmk2WkOnyCLu90c7gyJSOeQRGCneD1PyKJbkgRE9izOlyI/VE9UC2j0R+OyATZtGhS/Rzb/wTsLzPiqMpu5EDGDKoqW6DcbbWDh9S+GVvbsrd0OchhJIQfWn2TiUd740SHCa9CHQ7qHtNKZe7sTzLiXdSL8mXyFgEBFofmXeeAgtueEpaRJaOKofjuWI70lmBtdH7MhAGt8nudEfwuUUSBBxrQKlp7sv9kjfvqLkdhXq7YPOEAozfYhnGkXZyfx7/r+8whOS890tpAFoLS+x9WBZ5Z3eued8lCU71fw7WT8vOVZSK2mtlo+9RWqhapvDkhjwqZmZoW9mIrxQq4OzS0d5VUr6qXEpwoz7pljcBuxuZOujjP1uZCdKexfqIOQMprTXu7zE+wtJH6VE3Jm0Qe5MgUW1L8SL3zoS3k4IwPuwg==

superset:
  enabled: false
  service:
    type: NodePort
    port: 8088
    annotations: {}
    loadBalancerIP: null
    nodePort:
      http: 31000
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
              superset.enabled: true
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp
