deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgAYHb94fIW++L/3Ll9DOSdfTL4OoDBZ3WSn/TkabYZT6CbGkVT1cew2nxnhNYshOc7qh5n6SiYETlJi3LbC0iISfunXQn/zfcj4yjxr0AJsUunkxX5iBZmyfW45lJWcSuXBHYxKXxVr+SeGbkgf2E1JtqTtIvH6DI0T9Qlsqa65xroTwQf+dXMmzBbgZV+wFY+La6c4vDKPnEpaXUkTpLuGZpxh2EapcCtrtkjSSMurhUZ8PHA+b3acyIveO3d/RAZ99XZIsS7WXdjl/KpLntPXPJDFv3yB23XY8YZ+w27HldmgB+qkNGH6QMFXBqp/tyf7nvVc86hmDicRPtnB4jRgHnjOv2oKuZHk9rblR5v88BvgfbEZ3gOITLBk+Rhp9zngQYMHQ6c+q0siTyiSXw+SZ7AZ1/UwZfLweRCbMnNlPjDGNN8iQqdTdS9jRM+8Q0jUOtnJFfIOOpUtCi5dLuMoyauEKrgDhxgWiya8wUtnWGjEM8ZJ4MYjptH39riot7anCElg1Cerzvx8xYa7jGeJD/TMMmzn0nQl8zOvptPzvmixOZqZ/fgKHXDMohsZVZtaTd2QBa3z2elJk1Ne9mtxMwHdcWrZ7hH4H/ouaYeG/q9Iv4MkIgeSX6zlOqi1XY7RdLFVk6upnhZeXv3DMuVYtcLlJKAAFCli0DzMncwXxdC56f/P1o/3ZdPLDlZ3bBq11bag+g==
    CLICKHOUSE:
      PASSWORD: AgAGTT9UWWHYlLXMVsQKmnuaQzVPkniwGrfseTQDcrQfDs+ApSnNBIbxnAN3dSESpShPGXb6G49Qw1a8i/yj21hJlj3hhnZ/9w/nPhOOLR29oob0R2TkVOGoE6vbgUyyOF7SsyKaTzJCCGKdQFW0S/Vf68EV+cZBnStO87rwSemu1BE5B0h3DaAoM0LAsvEnidEsnpid1KIlJFM4xKZS2p5jprh5mLVMD5gM2CBwg+paVLJKx2dB8bIlj+8m8Nj8Z4ZwhVYlXi7dD01Z5DrrTYbgzEaoY7YfKxFxM8JEHf0HZGnovmW7HNjnAIwZvnFOr70/NnXwJzuny/itshq1+3ulNQ6Rex4VXah+r+skdAK1tol5fZnPeOIxNECKXBue/OUL5DsHwUjX5pD3h1VY7O72xUD42yuh1YBCkLYFEJ7XFOjRgF7QZYUz0Uw7Om7YxWMEOHWjzaS6M+dcnhP2piCoSQ6JVHQfymwrM77xoXWL3D8JrKNf5Uviyr/7RKB9SSsUG+9zc8oIzlX8V9WYK0iTOdzQv3ShhkFPLD85g+hPtXTnJEEMJoixlxA0XZQ2a+qQFa9sYQv6Gy9ktqGIbBmW4LaTvYqzje8umzNPxEC6NZV3K7opima0iGkeo4Y055QzVooQuVZKM7HSqQ0ydcpSelaNPIFTjhRb0yCWHbn0ZqaZkEfnWWhDzrH63HCV6gjH5rze2Q==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgBay6mkv+oOlqbK0dOb51lPeGpuqK3/+QzXgTEG/ogglukvh77+PH86WVRA3yGwEZmiETK0R5sdSPWMqwjf1lGDpzl9Zbuivlbb38b4sEd/l9p+/jua/d+Ztbw+P4gihBlbZgn1oDSSQpmRBZ5OOmifrXzEx6zQRcLEGQCn84Ti1XS4Oe6OQQ/QhEh6ffVWOaf1PyoEIUK5Ln6m1GxvPst5mpuZJWqR2HecilNjLisk6q6Rudbtidno35IzuQwA7Ek8v7Dy/lQyG7WAy/DnpPI7B4u/++lJ+5H6ekvXKlUc34WMVEDnzeZPwXLN3kxnDNaZtDecknKfQ9md+p6aHmrkn8LM4Pph2dOaanY2+gvO4eabb5GBp5TTa6RVJ9b/ES4R+6r/pIMUKp5Hy7S1fadLA3G3zgqeM9SjwhupoiYypv67AMpbFVpLVWU1iN5aWLr8ILoqyfFo/aDoKOuoSfYH33VQ9aEYHvUt7iyyQxUYIbDO6FHpTmwxbc2MP4rfwFGcvu4ZKWK7jbgTLc8h8yFRd/G2+i8NC7uTwDw/Sv8o7mcFVgqzfHaU4xVtSRsHFgSEw5//bdcuT/u0imVHOjRjGxP9je+yIEoFO0jQ4IpxcAqVIFd+xufI7z25ab8Sp8SfAe2q8bI2cu7S+2COkCMDSPmcIRk3k2D67XM7KCdG045nO9taDoUJ4UR6BQQ83KMZp1PjQg==
    POSTGRES:
      PASSWORD: AgAEV3pxONseole0uIFXqbim+wNjR7vhuVZnJYfIP+nmHvd4OE0H9YD+Tr5JjyyyfQ2teQ/iAEvTmtyRNVdSqVwAviK4w+aTfa/vetvIrQkEwF8G4eEit1oosV0cjCEan26lKhYRYQ3WsbxirBQTrb/949MI3kGNVOdzEFCuCZEBcWsx88LcH/jZBBpmYUpOncRKKascgNHiXBL2v7merCNk+QbNHJe0KQEGfpeRgoYruALOL/YsCiccYVOfCoZOf8xfemZbpON6iJjvUle6vY9ZkMS59VwPi2mT4eB2j3go5CEDrJBVR9ZpbeOKrrbSWUdj/nA5AzbEVGFxXFW0WH4fnOhOhPEZw+7jqf05nCCkppEEG0ykOmjjZRwnBtPfAq+jhxSovgkTbWc3WG9VcG9kthvy/oVEra/9gJtFbaOV+z6mftEggNrD5RF3x83DE47gYI7ElPnYsP9QG7aq2B/0qUj7iGspFZYiOyItS/hKGi4HXoJ6qaKMtn5yFGOG1lB1PtyQ73D5KZzFNwawXFPze3z640AbF9iaxddhV8zjSlA/994ewIwZvyXff/A43fX0IaNBE7Vuj7HPzwDAYBZGtV8cjnvom0xBlGV3rIf9bO/4Tg9iovOFMzxVRPK9fu+3K2p0F383G4VZ4TDA/WncQTo2QKE46Wy/Y3Wf1WmybrTRLeicorpXvmP4CUFw+mUeSOZ7aA==
      POSTGRES__PASSWORD: AgB0gR51qUugLZuR+r2naZRRpMK090U1KwFLHeJnPCVS+QT9FN7oM8/cE6RAoEt137keUtN6uCp7u0VWEqbb1quL3xWZN4e72j8wfNM64hoOcGJxs5iFy6bGI4oA95X0oBbMozFeJRzPl/ES/i1NhdpRRIu1UQV7/KMBEicq4s0FDvAs72UptV33/RRZw0/IBv+rri9aDkIuk2O3ZuQgntFm8e5OLwNh2pfSjQBsj+OcdJK85+uoeYXwgFAv8VANNfkeCGyateavdoNc5v3OLbP0bACgOcony1zx1jC70kurNml7pfLlJQYSfNIDkuVtDmy0kuC/PuIoUMW93kavx+VA47vtxE1rYjSFhMycUwTa8VVgDwsMcsJBY5b1zK1wvoY7umO7wwft+DanlaPEk1IEXKJEn3RtIXNDuTufWdNvoCOhsyRZyuwbiBUzL0suAEQPdpHZcnDikkRKxl9v++NtmzaUSZ3sAUyJH+yja5/9hmowATk7BJKIL4De9vAWVI1nRiaWZo0GEqBSA9WnMjplR75gYGei2rgaGyZrPx5en37TuFgjZYkuQkACHZlJNXtND/oxFikVMkF+rQ5Lm0h0EG3ohH56MUHPLdnBk8PV8ryhjjKXbAT7UJGIU4WqIl2Pz3r+Y8TFGkcOT/XW0L0w7A4N64FutSqKi780pFksPGBVdlBYER+kcmrEhd3RMWitWopa2Q==

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certmanager:
  issuer:
    email: muzafarov.olymp@mail.ru

domain: game-data-platform.ru
