deployments:
  - zone: ru-central1-a
  - zone: ru-central1-b

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgBCKx5RNlRnQwGAlmxtIzYb7JQyRcloWpO4PByuj9ilpdnRpLgWvdEGGc00rRI/lxTV0IZSF6q4xzkLXYZ7Xe9PKUBxzhVDwVQIQT67+djL63u9Af5QqcWchfC5jma0i0wgzLhiHLlY59X9+9RwPWcM09d1qUygF9fOgPgSK75oL8KcWmfWky0fxYyE/UBkh61Bg2+PrVmNAcBG8XbJKvQnK2h7NRNmyISZE6jatHWl0DU+92UAf0NYl2FZSAw2C3Lo28aDKpNYKgmqFM4Ubs1MHu/3pRg2LdQtOdFY+B1pOntE85XV9uB1xQyDg89ysC8IOpdYO2vAZQy4lqTs7ywpugg1KIbdhPTLU6zPf53IECDZf6KERji5DIcvf9Y+UYoHI4TiefumQ1u7FdlriyWFMG4F4TSk3Ue2+m9ZleV223W6nzWTsD2AOSjzZFAsX4HomKETMZBmLifCgErDmvbeoJctgHhDCgAQyIIjsbb3pnpDjbnpXkG/xHYvbfmI9hhbvZtrdxFJTC6xMlRy8kyC46JmhMZC0nBK3wjIjRDgtAlVHDyOHhvDm3n2sgJ22UpyZU0QsyPXj1smTIemwckREF5wlMKzpCtaHz2L7HSy1iXakBSTB8QlwrpDxAuvpjpux9T8/FW/nxdDmAUQw6vyNUfZkhADYzrcWeE3g8T9BpTWqdIY6YyJeg0XsnfyfheMOX4ilQ==
    CLICKHOUSE:
      PASSWORD: AgCFknkGBbJ1XGaoBPpRjqsvfzAJHQOUqRmG5skHsbRVUpmdr+OHAQLYlSlirHl5Sk+zFjNsu69b2R6MqyTxfFQcKNGzsMLMvxUotuIGYbI6lnPnbEyHUvEhicNl/GlHjm0eLsdQiMVHMsk2IEhtGyM5D2oVg1AT8l/bO10Xf5bnXEIA/DynwHYPapKHsjY38rCubCpAStxw/CDtD7Z5HpqdRFFfGCWse41buYRjxN1UWauoGuU7M31sLsNzbvo/IhR17Y4oiuvfENtiqAJ6Yu6jV6X/H0wI/ZfqXbtvOza/4wX3zG8ViWVZGbUTcRkbfzBbcBhkLOcCY0nc/xOLkfjthz2MN9XKeYf5Q9dnhpZkzItkhv/R/sIZdp3MgwuzkNlrVFk394xP78dMbt9H9pOa1LC80B3C+KOAf3m2d74CiZ9uEOvicAQwkOYmffi/wgC/cWtqbqMP6zX2XfZQUkTp2zX8GviuRBV96nv5ItdV9U5RmfB7ZsvKy3hJpkXUF20/tPg0agnPw02KI1Hfdm2ILoggYlvp2aT392NJuk2J/R6Ne/AE/c7dsE5p8i9VzJ524KtiulN0zhggsYiI+kMthpQRzB+r4VguOxDwPUoE9sXAb8xJzgwYwtozwu8Eoe0I2ioA4+sVuz3WaDa/J8pCsxowphnrb1BSBMqpkaNy9Og9cObtSnLmAXZpWSCxX9+hHEKHvQ==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgArlpNcI7kNbztROO8n1GVrhC6J1tslIrsgpDFEGll7p7AMJFT56ko5O4ubadgoYSWhsLjBOehxr0+/Wvyx62SYyLTbWJbZkkUclXWTj7Uth1n1xphE7lzDzWyBdtCMarMBBChMkhVJBT/4wkPXlpOoVKFE+brhKcXbDT0cORLh6rmZSxmLWJs9E8SdTbO9+tshK7gth2TpMQ822K7XRwBzEU9acF9KleQy+VjUQUNhWORHSBbG1XKzvzzwz33I4jNas0JFwCoBNy2915GMYRFXnQmZ9q7+lW2qGGjSvdFPlufIkCP65QAZo+cN85PiomM/bnqYB4HuZspuaJDXyIEiYRxJQ8ogo7yfMwOoJ7bkLQpo1NOsVtgy1aGIDLHwxCgHCl/pKIj2saikfUFLHrnwCvqVutE6LNRpjpW/tPADWyagJlweq1QayND3gIPzyk4czABA07u13D85ifFo7Zyb6YEIaVhGqDcDSOcKtTbOpKHmsAH1fb4/8gBSyDKPxO9S34SnjL9PvzDAWNEG6IOyQ6GyqQob6Zvse4l0TvvN2tToOTryGjloySMFxnoo6fX4CQRMomkQNG81qrRF9Z5xucWvZK02TswEMfFOP+mNZPnqZfYgGtW7b1TWmAY6WCQ3NP3FkGD/umy96Qehxpa9npexRusoVbRCBmpO4VpcyvTepRjq23VDaG00QlL1+9YsuJSYPw==
    POSTGRES:
      PASSWORD: AgDEbN4VgDVFl7PIM2/+3ujruS9i7/I5TeX1bEiP/0DyHtJ91MFdcPMN49LQ+bfQbMq5jHz0i7/1OwkMrj1J0R59rMv95hgaBfCy9yymYJnVe5mC3HCtbyCbmueVgDuJdGaGNy0w4auj4VSOKYANMOwQw3JJQP+k+wSviv2NSro6KK1v7LanZI7oUOc3IE7Zd22Go8OSVqZEIKwYX5/snCPGVvMuT6WK6i5Cy4MYA1EU0uRJ6krqIPD3qBR8ZLeKWwH94OypihDtkiTDabY4QAND4jChWmpckLEt4LZEJAApXlEcgPIcAihsXmrojp30N+vL3V9+fLXALBU2B+Cnw8UQUQtdQI003KbUJi8vSzmmWohbNvqPVaWAqrqTZqPn4+a2s87vOa6OKh/5KcrSMXxArA7FM4VuPEpX8GQ5F1qYquUtx4QccpbNVsKEBKDuSs3GjcvW6mnGjU0GJC2J07BE1mUGKBeUxtiizlUs9dkKp3yvTLQSACLxNKEaOppVr+4pT49w07Ih452LFPLYMVr7x/X77Q4KxiYZn3yrBJkfwh0uQGSBESXZPfjTNsvlrqoRM0sz2db3+Ns/KS52StKketf3u3fOl9l+61wH22Et1A2L0G1JvYB7uxrBgo5geEFPv5/8eBo7yJSryxi4wI7y2JobW7OgO8GNKO7X+pykfW90nxn+jtIfU8W4E5gve+Y8QpHOew==
      POSTGRES__PASSWORD: AgAVSyXw5WcPV95ZBbtucZKblsxbVa7CJGPJZ3A8AXXoo+g+hIrQYtZeLdYx+C9b3Dz0W0F3nDdcSrB3vnlCPlQkVHFt3z9VOQVffhIM5CSGfFFWRTv7B9XHITFuBJK/R8B2dKvOHslOzac9SRtUF4zzCIdSh4tCMKcUUfu4Gj+2jSBpcVsQlU+U/GMxNmYckvF9TRyTP1nnNpoiaMCV8t2H9pFXbezWmmsoexIn7VxVEJcym6i++kf/bntpCk3gzX6HQ/dW0ng+5M03fOZfvnYd5yfEy5jOPecHEcPGCzsCQKf3ZpXCbVj0UscGdSYZKFF34flxgtbrWDF7kqvFbNcOsKWnxe80VRwUn1tWpkClpwF0VycheDTj0olMtQE2/59u7ezWkMMYmlZKeocBJ4B3szRE+wAlrLU0YBZlLvM+Pir5hvLCMaZZwFYUmcozYZgXu58esZlFBahX9kokAWV0zQcznb5i3CSyqP5UJVdPpy8h3sj/VT+5X1fDzDEngfmwAFIlMS5EFJZDLaI6BMxqKCzgrihiDRXXGxwo4xP7vR+ZPfziQz7nrMpf+skBjQi7y5s1bLZVY++WMyVGQFQoU2+mKfTEtYbTAlgRzlCUXPPYzvvN6wdg2xLmFsZVIPQ3AlIN3xUzJzsVwhY9MWrxDdUtT7KxFfNogSKRigypWa30eowUaECfGLlWC3uhunZ/7dNDhg==

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: game-data-platform.ru
  use_tls: true
  argocdServiceName: argocd-server
