deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgAhKEBNWTXnO7V32qgD1uAXlzmsdymJeCz9KdMP7Ln+FLjry0VAr3ZMP6D+K0lchSTagnu0LumhSuAJfnjSnpRRuWrr5I2YsHJrcYOTHiC1K5sanAIJizYPJW/XwVGs6PaPCpTLf6R3Bnrh3neAPbJiTChd/GEyVGdnv3v9gygfds6N2IBfMeoisZdN5Ri/e+Ri3szOk7LDAfbz0S9u6drUrwrxdNFcrFPINzqnp2d5tmCBVLpQmxwPGSIYF04pL2Lqin5Uc01oJ1VAajqSGsH61/uqm8tnhL+R1MUXNLARU8p5kSJVt4rHBdbgiLZVLjWaebmNtyS4m6OlU8eiPq4wLFZ1f9UJljLJMgEqMaZk3Qqet1SHF6q/DPgyzp53B41MvrErV09Qr7skQ1DzQ5yxJo46kOWIf7SEl4tIsfoZ0IH17AJGClg/nqaqpsh+cZLqbLrnzwpiAKI3CtsYTWinfQZ2Zf6ayRPIN1bVLM5sDOLvRCoNE3FCa9bsRBTUlfixXTxMVJHRA7lKyeSSUlp+7416BAJQb9Zdv01qTkRiYVK5i8dk7q2/+t+5uvPKMZQIkHFyJHS31cVNkG7yv1sDb60wjW+cCcB9miz3HUiT/b/QLrELKZVv8h+pErF6ye4biuy124Z1ZMLBEOtR/97+tsQRAuye9+DIF2nUDNtYQWiXmy7LbcVLfN66gSJy4EAR/wZNSg==
    CLICKHOUSE:
      PASSWORD: AgDBRIinb3Sw3wjttzcwMkQnzyE/DglZyE/gvssLH9v9NixDyOO3L867rbE3GhvDCv/OoEVZvl1hjrlyplL5oO8nikJYzI6/N4uERTR+D/ddNwHaDK+iB5BywCOmwOSUmrCNkcqcLJcQT5lzQdTd0nkDm4Sd8VU+Wsm2BkG43/V48hHXsmLjpg6GparFEMVId64o7XKFhr3AnSlCMUgMYBQMSdfY58lWiBF/RMJqTwxA6O7lcvhQk4YUU7dnNHWGGU9STCOO012S/Ulw1BMKSqH3GOvF9Q9NnL3YHuTBryOcVkY4As3SiBel+92zzuRLwoc0qfVwlenoU0rAXXCv7x4D3g6C8u+yb9Y01Pd3SeJTfOdnPc+r8xEm0NJJa+ZNAFqh3b7/4CB0cALl0iTlj7WxJ5P0j6/bL1CWn0M7SkV+5Bg5JZYTjKJgzxkslt10cGVGHpmUu1exNeNPx8Yer9t0QGiImzVrhxqciR51uCK6qRYztl1f6Qbdzlz9MISLkR9w4B717MojI+DHWvYpSve7wT2ttB0EgPDBHrzXJuX0FCLqnw6L65Fd/gJMXthF2rHnU83bo5y/Vy/l/KwObhwQDhkcCHou8as2PcjG4Cm1flkV8dWGfjgnCM0o2v0qngB4Ru2fWRoTWkZHmIrIb9O5Sl2l6UeHVO3F/JmdEGF/Zkip/suP/31Cmhl26XUQXVPuJq3xbw==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgAE5fXsYf1lRtyKxqbV2r0qxY3al6XMqrnCM3tzfN6fb6DDSXJWaLBcDAZ8XfVFVzM+gQupTp9F8sbp4cGd/DazRi2uDx19+JVMsth2ggBa3zScmfv1YV0ECUBI2DiNfEyWLOcdp4fmlB78DHb/WMMjjyzFQ/6y2YKruepcWvpUFBeuSvRjUCBbOcWno3qbMdFMkVjP5svT+lNzQHZ9glBw2ER92u4kEnn/4lCPwldYxT+KAnicnznpTiGSEv+NjyWCWbq8REOO8zcocx9KTkhAqSabCXl8Ki14OK7cPzTTZcXw+6jK0k7JkzUg7KMrZLFMaeo8fLQk8SmiqwJuEMR4h8OQTOcVpDAWl0Kf4f15MO0WNsMio3Zr1UUpMrkvNjXGUEGuxAQarzqTd71PJULDlA7FogdiXxrNPaVduSt3BDjtjYu8K2+GQnP5VgpSbmwvuG3DtHJnWczkyKYqGiYnGCpTDLnjrcMZbYAnJnS7rqOesnXDo61H4GEP1FJn0KYIJCLqmIfhQry4GT56+iSxRXUfSku8b1IJwBp0UwxSsLUHoxRyQGUL8YUWRLqIHvyadNtZNGCFqL+FQUEv8m98k2NaQoI3HjYDqfImbICqA7L3Ev7fHIAMYG4cwGTHkK09biDzDqcZr05vinCLk4v1jYkQHkQcRgQte+/g+hxZVmE+SKVLtMst2MvBQH8imUxs14pGgA==
    POSTGRES:
      PASSWORD: AgCnUa9+VHGOGEQJuF5jJMa5Sql/3aXcc13eIGdW6u8RN238kueC+smbbmwffyEjWuk/08uNPQp5wFYJoOxO2dpEpg5sN098O5HXAyXGe7thvZ2X0t5F1Q0DN7LN8PnjdIqjVM7EIfAKvVbCrovRIhfZxF96dRr0K7DrhaU2RsGRoAKqsLsA2SD+66zYAdUcsl/2cZoIjzQLu1xNMXZvMbcikCqf+9oVPH9Z99vroHEwL0R8fygDpZLa12PC8v9Sn72XYJ0+jblHuYbQ6r0/wt4XdVcWoIIyr+b0G7Iqucf9jpCYeg++S96ONkOqNZ2umqjcvcdYUpn76+ZrPveKoIeeyPIxLOR9AHgBhfRTBJ2VP+rkqiIpHU15SPi1VzPd3oHrm/qj50GLp8JWp4/mZK0L6RzgWJ1HuanAX177I2oIcvmXpQu+ZMF8lIDXwxw/5j4P+ZO3mXyGcV+6HuWZ2jlT4OImK5qdEdI8bUWXfb/9InN9r+fFSl1lZI5qmOkgwy4QZvTOAidA04kWbn9TcLpdout1ybzTDwWt9hK6+3dtq9oF5nhL/gv6AP6n0E6F9a9gWFOisHzCOKg25LRXCg7Z8IT98RUPuCfgLeemiSFq32gvV14vsymC3jIRCihC6Q3qH1XSMr64GgCEtz20HkK6wMVSmSWh+H+7G9DmHKZQgr3f1uI7kF0GswzuUUYauPqZqwEtFA==
      POSTGRES__PASSWORD: AgC7pmNfXT6C1W9imIHaWg/5Jog6nTFsfF9LOxpYJA1SbEpviw2xwW6Ze4XajOU9KG1YAt3XeJqBSUFtlz+haN69P/+VQICDj4Y1P5Ix17zZp2/1obao0lEyjMal8HzrEyUs+i5cE+yBau7N1RWWKxWMxuzk9tWk0/ledZ3iEYmQnXckuI7OSnezH8ktKAmp7pksjXNYhLUvkltH5m5lIejCO9Ckmxs7N39cbirI5sJCOk9WRZOUbUIEniNv3Parm/sFpO+WZIzkftMv3oxdZI2Gj5nHwpfVTnR+8lAWzqAWiNIj1/Z2wk0lxvLJkJyZ4ouMI5do4e7qPPLDWCuJbqROLqrFEZiYwHZ7GrtL5udbrJm7f1RF/t0EqZg7eYJC3ldMYDU808AhKWz/r3sZmLN+h6EEHtT4Wh/sElaY3sK1u2LrHWXGxYFgtuC5dTn/Vvd2+rGk4U5cktp2xSzueRVIM3t9HO9fpfFLscVEe+Mdb11bw9IxwsU/LJ2t7cNRLbuWGs23akgaUyOkruvDpZL8vFSEbuqxLbFFP6D4k7/d5C4JG399xxI3nAmE2uBdtms4jHM+7CDQ3g2HAitaNco9rQY7uWk+4FzOdatpqG2BW+6z0sUFoC3J9nHj4IcJG1WL55WlEDUs8Yvrcnekue+fSaEnL3i/I8gwllY3S5ckohu53/hNoznQ7rZeg5Hn0I0rDOrx/A==

superset:
  enabled: false
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
              superset.enabled: true
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certmanager:
  issuer:
    email: muzafarov.olymp@mail.ru

domain: gdp.com
