deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: session
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

  flink-conf.yaml: |+
    slot.request.timeout: 10 min

namespace: default

command: null

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

applicationMode:
  jarURI: null
  parallelism: null
  upgradeMode: null
  state: null

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgAnhrjfNODjZPyPzJwrP0WQZ08W2YwxQ8FM1RfLN7qTsPWYxcBE13rptkBa1oT4IoriZFLCbmfiuW/YH36Xwiq9G0LS2QmGpWs9RHZjPvl8HqGss1o/9HSLfng44enYZEGUDcc7p1FL3dI/+oGrrzUiqEv/2OTaLVR4jEQjkRAFL7qzW5zoGC8v5AKYO0xAgBOCswSQu5++hfilrZFkZoTcTC06Oaq3VtLpKFXx+R9mNwnbfoiFubtVxl+Q7KzAgsHUPXrlgMc1SJTBBL5xufK7NJRtEMRUKdW5wSwZ2f+Afmkj2ESGbK3TXbDLJNWD0HK4gJGnsqhjpRoH3oFe566SiyxRs1h+CYeZws07rJYW9P27ODPPFXl9IJmuFiuQ/JBnWCCEiIT+QbgUs+qtLqHT2erPxIBuPP+eoFjqncGZulKSUuU0uwix2sqiMJ2bMZC16kEyYYnD0KlT25YWC5TMbUhdA6hG0c1HBw/CLyksrO+k/ETlzgPLHyk04gmGgUDfANA0eQ0Ta9bo3Y4W9SgBbEjBqzhmbA1vfS6rMSTrM1KNMSoLdmgEcEaGLXqCUrbabdYyDYQ3z2JIWuwx1WytUWuL+DmDSUXOJmiC33FIlxI2cf7UoZA3n75HuWCeXe1hu9/lUg3kfufJ420C9HruxPQRxz+MuurBL7sqWRx89/+owwI7ewUo0EwK/RRTSQITC7Eqy8xnmyo=
      LOGIN: AgASH+7qYmKS7DP6OPHcR7tDviKBDToCNC5k0leWByOatyGfOhE7qF1Y3010hPzyjxSUKparNyTM8EqMjxjiw9Fc7a87bM1A4b6noYKJgeo67SQ4e7bED8L5N67fMrPc0qp/UGlo3zLEtiSJaJaRDtayjyqvv8OPjpvE1hNAWwxjKbf1g6HiZKx0E6xARmjOxbn8k1Ywmz5hmRq49ZvXvpcJBslZLkIDjYT7Q25hehreFb7ht4h6nZ8tqc69HFcPyAAzlsu03VQCGD7XqeUIt4FpP5CMNOp+N2/gfDMH8JDg3vwQNfgKxf3Wb7oukZOTAAoV8KNRx/zDnxxn8UN13iEqHZm2Gt5PhTSA/krN8ZvH8se7mZltezVBmDH3Qd7YaepBS/lEqU8VJ4bAII/ZAQxtyRAglbGMnYS08iHVaOp/JXyR+ph6PE3YWYgQa5rqareHsd+sn9KXeoV/sjWOZqrYkSBWjiGSvopcv+OtLkDLEDQDDVWUdLmS7L2VDj+mwvuBAPzZILvBlPUiJNjlKa0pQnqgEONrAySPdP7g/sp7R0utuRdARHKhCAzkyuRPf5MHU7LlZsQTSSUEfe08TgYzzD/63fHCIyVhdEGOQaYy9AS4VaMzgkeMjCEvuT1Z8QGa44lXbOfct4Ugatkyeni1GAu0Npr7Uo4IRLs/NfZKYgbn2zdDidEIkXKlrHunJ2s1DgPp7N1Dzw==
      HOSTS: AgBUbW3vNU+LAW8+/Cf47dU4Ahax4mveNuEfBadAmVu1hpAPpk1C8LD+T6PhIAIcw8KKkFnjUy64xjt78yh3iVLfp0kyFtLZVJggKUoQzwhWFYO/6ECR67BhJYPpj3pJALE6fKtnQ4BOZLFSL9v7E/XGy1IIRLh7pFaS4vG+hfCeayJ5+aIT0dtGulskCLtMsy395HRhXvms/rg3q1STkvImc7MVIdB1H41fr1NjefuFy8IOdj1U06yDzaan7w9SfFGyXxxYwuzUUtbWgRrHmmOCJXcOZ5Y1JKYGMgppmYtM4b5YZWzqAi8tNa6Yp4lK9t0xZ30lkFGZsy6ut+djfnMnES3VJIAoxM1Lq6SIW9CgqbRrJInvbvh4q8FWV0bJ/9HvZuIpuCJOtlGpQQ/VdDjFChe89GPI3Y7HFcwyy0XL7s12b4U6ED8almfFgWhQbK9JrI6DaEfuosg5J0WTiZj+STdmkhu2ggkzAZFVZpd1R6LccTMGdU0eMv2t1MwvtdpkLfxNIKONIDiq6LpVqo8VeF8sLEVj0x13IXIlZOgzWJf4wRbkNZf5XXfNxlxABm04ehscTpP7NP0G9JKbzlORdzY489GTRJ8jB9K+ajmGjueE9LGtp/xsZ3wJizdhYsPuvYvNyTsVkt/og1z7lM1ZPpdV3cX6N9xNW0CPTMVtrZYxZq+yNWaKndSzM58c2S6zElIg0HEw/86NRGsGp5eM21Y+eK/IbqNcD8EfoI1IRwv/vC7qkZtWXMtwtbfy7lOGehbGvjbepBCmiO79/Mc3
    GOOGLE:
      PASSWORD: AgBwHEDOmqBtBCAGFtAdx8OXvkK1DEND+LK5287RocAr79dmjWzAxqUSElDynXbGiTCUZmCsaNGHDGj0NWBBu/3d6PIBe/Dod13OXG/iui2as+1F4SYodqttB416fqKbZwF+2rCGdIuusHTs242z/RZLayVAQDhuFIkC4q1Yf7QHAeU3eXSYXHPCjzsLN0Wgqas+8r8Ba/m3MhK0V7jXzqQx7Mb6L/YKFZn3PxJX+IIAKySMBcKS+SIHg5BWy80hh20q3/rCnLjvjqcYCCwvs4Ngl5CjnKAOz7EVywFS6xDBdG8eX411kHcxtVb/mC0/Djc6KD/nqYNfpsoPAH27KWJlUjrfsWRrFbrO5y5CgZv0YxmIL3MShGJASjv9+ODazejxA4aU7vB5jddMvHw3xq6ldMqe+W1XpiX5k1woQOUquQtKe/4GI2nTVMGCfcEpb7BxisghTrkgNsA/sKANooKwA2TPUU7iUz3yO96eHtO6ohBo8qUtjd1VWs8XergsjwklSXu6wz7Mj+b/V+Z6EnoFLUCGz3t4eSar8bhw7AwH8bgbRi8bpOX9CKFQ0HR/8ZKWBIDUXSMijaHzb0YIvx354jnMGlaqYk3vgayq8pUt0urCvTG6ar70kU9eYKqj6h1dV0XtFUFCqkA1o0aghiIxeLI+MqoWqaYQnMZ+nb1mGrr2FwOjYHaQmdRot2yQSGUEKbe6
      LOGIN: AgBzHMk3bhT9uoq9Z6VueKlWb/woIA5HjnxnV0C+UeccV9TMsPjTR1Z07L7XSpKwPFvdWdGX4PYR6lhARrv8vVMtkeyzp4t7SZv3dy3nt+MteoMUhHMdZYTRl6Tuue0FohsSnceUbuwThvgEGcH0FuP+ladt3TcEVbFn2bw8+eujFO+OMPUrI3+hBcxQzIMRt+xphacg3FaDcY6+2RAoYgMKQWnURR2jzinUVKcF1nDpLZlE3w5atd8ciKtQWffY6EpkCI/C6IF6hkb4qVbZm+Xkom5SSnenMbvdG5BXuxMed+4iwsdhmONiYA02EpmJfhmllkdSq8ebtavdhOa0dgb7Jl+Hof/ccGh239cFU6nRCPHBf/622x7IfdsVhDz1Wa7Va8ajYjpGj9Ki+pY1hl8QARBOKS1GJdD8UyzVyZUKbL9cMucfTCi3J0X0UBcImRTfty5MnAFbbvxRawy7mDeNt0lFQXUvLfiDUq/miWxmdeXa7BoNI+OTuKnOV1emrosgdhUDLHaDdbIm1pX4rcB8+S+6u1OR/z5vfihUTGTq7qYCknd9cLJ9RJXouE/RWOa9AITiCdqI1pD/RIN/uiMBdIAEAwTlVQxxjDdy0XOsI2U99+X4tmZh0XsK6V7YC3s2OjT5niV9yjEtq4UADgaytHTZ4d5678sJzdtjhTY7Dj9iOo7M8vAILnrjzUGIXn2lTd0a
    CLICKHOUSE:
      PASSWORD: AgAmhwjOXSk+xbxiADlOZsPBe4WRJ3xIqZRAqxaP5+Yzdz6gv4DC6hEVW/ApOZqyVfTOOwnctD/ykYonuZIbtKwJRXir0DZZwMXpx0Tv07tIzgM1fG6MSs/8oseRZ1R7cWkpOc5vh0prb1e/+QmmEAyHfhzLCxFhr9QnIQiIV91pocp8MfkxnzwqwpFP33JvSAETLfAjrv0GS+nWvQiudgKEBzZjxeTilnKt2HzU00eHyFVT7l/5h9sYXYovP5YDRyxpZAhES/P2D1Edzmy662aVis5eUZD6FZmkccsxZeFd3y5uDA7ZMFTHKa6pfJhpjFV0EDDVVerN4WmyQVnOHiONLO6rsXIMwTB2M0kq0AX9+XMEK0ZEj0ibWuA6Gukn/1jsvU2s7LJXbKTFlMpglWsUeoDdQtsmvkDWke2fw/MLI+wyjj4cy7pc9HWw80Gt0HOQ3aU8WNHTTaj2A4wOyeYhct4FsMtcl6NbbG7TpGCgOgBnQ2WTrOeWE1ROM5cU95Cn6Yo1d05qpe8g9EsAFcyl7ObJJbfIbUrPKg3jDoY9Y3RehApcriEKNAW4J42MFf+oVlF0ZNB7ws+6s5svrdkuWL/AnB9QK994p3cY1mgH1mAvqtXdlr2jZlnFzhSLimIzLT3LKYfqvRcddZj5heQ/mqfeI5gIWNQ3lE+O/fi7nNSw9e9Rblgh2zmG/og3lFKdc2E=
    HDFS:
      HOST: AgABMa2K+pn7sGBaHdeSUJkDjLrzeElme+lljMe1x96mYVfKlF3QvYsV6LfT0sZnE1lC786yPCHOgtYbZelGO1C/TdhnDV7IWzJEN0lekFzSyIUXrCgVrmMKLGkhi14mXMpfq2XYyTuxGUH8Jci2l1nvw3Hszp6INuNpaXG8UpKUbrhs5SmttYgCrqmaROT8DYxqEOSX1KHGHwklKDil0mZpDkvZwfC8M/ArVRTIA2wsCP0EBuU4m9miCmcAgZNtbpRhh8TbOUk8pj9A8oZyqfkElDggH5I/GH80Q1jKfv+gwNBXSDdHRRlxuqLeFcGSaTQNIqGYvcCMKjt71ttrYilHUiykDZFuDRHDPEToeoYxENIl60ujsOv42VK/PPDUVQsQdNhm+yYLuf3IYQRVJ7zTxHe1Ds6noIeWm9fKhBgKLqPVNS5D9aqhYYhVymIbjGv20subCtKoe6jNo4gIfnBS8R6BphVsUDfguNeJZYE5Nlpzncu+Jj9r90jXnfiM1R8AYoUpRDNvnwAbblFKEaEpw8iuGv8IpSBTTIj+721JNdsRPCaKkVhrx5rNR8Q0t9gP+1mFAlUC8adD1VHw6j+7Cek2GC4Cr2ClnnFHJvpITUqy0kEPaIuFzpDkJT4DNe55gMRJD4JySyWbVlRayJgbamJyuWs1xZekD9mP4BWzegEn+6nTsgsYvEtxlZHOz1adyCGnua2JO/wjdYY=
  SUPERSET:
    GREENPLUM:
      PASSWORD: AgCMopEILtKG13AqPJEaDQSyEdM+wlrYGXldOYNFszw1mwfTGyLqIV99B2y68iAqeerm9l87YC+BxiEJXIeBVqgFhKPm6ilh4+qfZN2ephKSD2jLM0bCcjC71deKP7EegefbI0c1hIceIkqYMQgwrqAmUK2OXNcUG4ccRuGa6BS/pR2gqwmqDMksbK4n99z3macFHT+n09A4VAyuSYS5aexnjPvi3gGk2Y9aOdvNrdikDM5ZkMn8veaiFiZtfe/Fc+VeUJ99z3C7BRLSHqt1GRcfCI72aHfE2V66yv0DWIbkxC6haURzc2x/j0P4MHwbIpeiyOaWUdHM7ZjXBrWFHLyG2agmvAEh3EJMGqDyoWbYNQKa28twiQgQp/N+Pax0PQoNj4E4gAVbFJmWrjHOoNPEMwqN7/0ElxIF/x5/5N0HJgOjDa84/8kLxbozS+595huwkYHzOz/fMDqOL9QdvUziE6Tunf3MIkrzqnuOM0Iqy9vdCwFSt2RXlb5zmPj+SQkflhXQ/g8AMUeLUG/EI78B7mDD+BwwLpDezm6ZSR8q4V6+eZ/DQUsgw4/azeWmEC/XY7inWt/yedUWYjb4I7iXmqG8bRdtWvUW5a1ZGE+NubKttzmPOeuAqujj8HcWb7XX6sbVASxOZoEn3aH3v8x/cS91HHws4x2MMHtILI15PiJkq5vTs1hlxSJsL2VPnZKh4c/f

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: true

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: null
  use_tls: true
  argocdServiceName: argocd-server
