deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: Always
  tag: session
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'
  flink-conf.yaml: 'slot.request.timeout: 10 min


    '

namespace: default

command: null

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

applicationMode:
  jarURI: null
  parallelism: null
  upgradeMode: null
  state: null

tolerations: []

secrets:
  FLINK:
    CLICKHOUSE:
      PASSWORD: AgB69GR2MyaQ5BbjOUzHxKOm4R5Rv0HOlvRb65FEUOECVMTsQ1J2eqO+XtQR0J/bIoiHXt0aeEr1UB5SZXW+wwFTWM2ua2Mreg2nyIbfykEfe4INuopDy2cVM1NMeIIzZstBHywFYOSZuszyNF3tZ0eANIhfT1yp0SsNRxsXGLp8WFDUDndpxJTWWkfqO55nXnV1KtTZRPQH4ADocejK7X8VCM5fkOBBdAaziDtISH3PZs/ydiyKiKN+ncg9fdF9Jekz032T0od0iK5mMQg8X+KkDU9mpFgKrbnf786I36IHRDnp+ZrGwd35B2heuKYAzCy1eddAIYnpHGBsZl31zBp6SpKG9Ai+xdBmCOlu6Q79pb83KwpdriZpcCH4SoAlGl/DZwDf2qIKmH7FE0XmkjhvKePW2P7ib/lWrK8tVEnH8X1NCO0Zn1fp+fnR1OiDtoWibdxJ8MoUE9wJzWKzUCVRSiRRGJtY7Nt3BvBUUcoI55/J19p3zWJhsEe1qfwKMVwhr/AtweGODLbGg3M7F2cg4wf1+ey+ONnk27mO0Wc2HCwWU0fhkkx22LE3t0xc2xNM4kG63NZp8o+ZUPqyHxcyILxF7dYEjBRpGGBG6p7z+Fk+nwAlag3tBzdy/jU7ISxhnSJ0Kf5cXOZTGRzR4L08wi54moN3gYZ7ofv6jitsq9C2CrX/LLyFekDqM+2P16xxQKA=
      LOGIN: AgBfUXlRN+mH2Hu7kSq5MoRvAM43KESaIPb270L+7xKzuN79JgydsoOrNe0rfdbD5u76elyiyy8AeHj0/3eadtGpd6BxeGJyGOF8+TBJiUwkmFm0JoJgfAurbX9bfV4EpaHUbgO3FEF59oBxR4Jg3ZSd1SSZKSAD5ryOOCAENWIpytL0JVVN3Uc422zaeFcmHWndN/aAFh+40SvgHR2cmdLf1jyw+M6gplXtrB738mLSdsrbwzXMm7lg6lOp+qxdKc2MhLa2CNPLIUIbxnPc4eserxBSjTA2GPekh6+1Nj+RLa+nPB5v5H+lwZsCE/cpLWvzo+St0Ruse7dr0Gh+GI0jS/L+/DUAN59UXB28BgjVFJujaWwQprNXuQbFsLJJh5AxYfDJ1udtf0PKIoxbrPpf0cysv8e/ujm1lRVgd+hYgsyHm+sCvvnoTmT/JONSaxqcnZIgE8gnWjolNsDiTHEGOEwS6bIp0xYHWfr7UKa6bMIHoL8erfFuYr/a7eiRt8odLDFUk/efM/r30IPq/teIRkX+YHMsQszdtrO8CIijz+uRHVlEVAWrLt0Wj9GYgRMEk+5HBFl0LEmBsYz3bnc/O5huz81RTymJBHN9fMxbSBz4jm7ghnSCIZI2TIsSm5Zyh0cHA81vrY3amcSNMoHqV69EWVE83R4/5J+b8WdPr2jyt1o/ljtDYTamwzuxri/WlU7O0d3vzm0=
      HOSTS: AgAzAsg9pAF+ZW9NYI4ufKAJdPYhg2U7l9G46VZUY6X/WLp1bfIYI88dAx6e+D9Wt8vlBnp/BgxzMhb7eJlsITRJY92edMWR+2KYXg0NUeLL9tYYn4cB4VsyAoMnivI644nQvnVvBQPpNGXDPcHoQZVBBJKIcvVDxe56QE/5fAMzI7l8jvM8tT2xGQFs8vlHpm/ygpO70PDIZIA6EOvtsNiDJqc/TKx1IPuZRoXKNc9nsZ5soUMi0sOmsye0B15tKsQYwG56QYkrTzeWchfSUxlh/6NJq4o+yvFWr6+txrDpODaqk6LiyftQfHh9JF65aXeqgZyz+sJ4LP71FTURK3342vetFEMibc83k21HTL1huz/bgaPiFnOV3gpDl8ujf34HZM7IhoiApf00nbcMLyf0xw3Gchoe0b2A/D6Hbu5p2rfQWxk2BVQGU7EwLbSHJhhl4VAgcYVvySUjv82D11InxxVJNweV/KILUqCUi2JIkec9FeBvT65cZwj/5yUXsRgn2lDIOq9tgau936DTaiQjmqdGf2Ztz18UBuZmtm1DC1+dLNiY0sgeD7xVOl8t3xs8MlPSHOlErY01c+++XhEu4aSnIfogiSqD79hBXA2O85dp8eZ6bkETtDwLRu8mrgLWKXvxsAoKUae/5WbSvrUtwJczGRFin+fLME3PVVt7KmHy7Py4l+TqVtA6yKCc7tz766dlKkwTjcuGY+HW9O7LIU/87C97qZs+Fss0H3P19FNWmazyAUG+aV9WgYc=
    KAFKA:
      PASSWORD: AgBqtjPRgNjz698bHx6OXSirWZYzaKkKX7e+Xjyq6dcftYE/aQCsWTnvtJZ/R4Tfr7OeXKO39+G4bCRAt4UMMqw298PPjla33ZMg4xVD8oXRshTlkYMzaFqtOTVj3AWkIuldAs5yLFqMfJoXADjEUDshQ13pSOsC43ShsHLttOPCbN3C1jm0hktfs/KtEq+hkFzDmsYdgnuk4esRxQYeqnRRH5KoucwkWQppz14GUhOvKSPTtIVipHQUGNsqTfDWzGy5kfxSOCChRQVeWgebmbt82qhg2QqAS2+spvtUmxVP4isqKAD6rpWqdPmpSb/7cj74Ky/g1gxnX1PoY0bCbyW5y22Tl+GY3+9Ejg31FkkVzCakvsWt7A0Cmq257/qN/sWSJc7vpku9cIWqtxmYroBM9s3qPTVXeeFSFTNuCiJ6896CyGQYMYKdN6P75xzO+E6KZ+8F9whWHoOYjhUKE3u1O2zWen5fR3SRH31djDLAf3vs/iakXAJ/CSAXfiLiQMjI2PbC/VfcNZB1zLwblGDfMt1BVNfa811EYooj9xreqrrCw/G1dO8sh/RJJAolI9lZr2RzI4G/3Ag+/VHAEhRdhlhUt/Zn4zsjsXZjig2LpYiWc2N9LHaE9Zpuj/QIzVIOqQGbdq3q0oCRJ2jbh6KzPlrXIpMuAnD0Z1TPYeEQ/lfJdKzhyj1icS3iTqFhKL0avmYGak6DpQ==
      LOGIN: AgBdsIsUzsFag+9ALrqI2RuLpSb/dybsBfVGREkZi0LZQpfp4l4WmMeKzeUZSAox4Ve6LqVlv8Sa23HxLzhcQZzshc0pefeyNV83fYfNiB/SwGpg64Etuqx6wCHANqCchP3xXeTU5WAYgFpIHgQr09aNuWRkIbkeY07r4+RIFqY2UADHLr08orO3Ty7g7diB77zEtg0VOkw5f1Qv3IDZm7dGxWWvY9voc/5epSnf3to47HgXcoQA/nDPfQTnJPGqGFryyVsNfn2vSnrOIAi309itisRDZKzWxxVoLriF9B+/xIK4ojQ9OsQNBDnmABnPj96n2sEJAbx0O8+f7DeU/02kAxAfikqQ84ZzqG40tTyUAT/UmeLjb5aq8PDTVhRGDcgfUjeTP3jJczvfsV2wt/4x2SuquFoFSCWxfQRjLmkan+t97RZm7J+GhawyC+U/p7OFFOqnpNDTI6m79EYdVYqeSJz/72zdIYTMcGUSm/UZ2Q6431Y9LB5linqfO31pjl7VfemMwH0eiPLJOnyb7xL/PegxrDJ+WcA6MO1az3Oq8m1Hza2LRlfZMHMbLTXRgK63MxYaICRq1i/84R2nwS4icV9bayf2dPWWs4oo6LjX1muqdoR4zbBoF3frfAsaPbRJJIJfflYqo4m9bXKDZTgONBnPGANt1azbYrIcV7ugUrjbYakDp0b0++HGUUwoYCCqJZ7OCm9xoTw=
      HOSTS: AgAmSOPmeLns90oglqfkegn3qGY/dI6KIhsxYsy5KIsOyy1xps8ebEzKuRSTeUmG8g8U+n53UyxgqFGsxc886aoJscG2mxBPYRhFK4njO9WBkn/joNCgzMHj5/xH1t7p+nZoOR5ITCZFhSZuZPmVfqjRazXelSl+fbSnxw00Nlv203GqdG9fWluqsSkf87cSz/miWy4LWqZaAxEHb671V0IjqVBMLanmeLdw3LphYELIxWDDdnsPwl9DcyZKbApp+jfsXG0mBw7QlvVq/FPm32JWGyein5ivterDk2w1h+f/9CvTR3Q5HD5aZMx08i5+xrPYiCdYNMCSIrwHaocdqFyfN502ieSh0xeDj+cj7KmlJmXdcJlsfHb4SWn+kOy3YQ4vBPmow8PvewoLppFAmjgunHPpYATPmV4bS8gEZbRKheJXDqF+Je9fAR9QYdz0VTqf7xVQBp6af42GoOTlmc/SRDmq1L2rWqovR6xSRIuGH2+IlSj2VM6WznkAb/OTOlVwq8ruQLMdxlWOa1s2XI9z8TPNW0ypexS7qiJtVE2VdlQmZoIH9MJ1LIlsd/TLYt1YKSB208P+eqmTKvjRULjcz7lQ1zN0pGFDOHVZ3TZrkP89KxQvSTsfDffxzEVrinl2gGtkPDcW6QdFJzitrpySzdEKdS1be5uGx+2/IRivOObEsDc4ZBoYha91/NlzZ7UGefLn/r1CvR038CXjvOyOH7hs0IN7YuN68EAPQOG55YwMeDaS/jxrj9AMyVmiTvTbwicTB7/l9bizIny+3bqe
    GOOGLE:
      PASSWORD: AgARRyhkkNsrKWGLtCxYaQe8A7iOxl2WlYHnAzcoh+ISC1SNbLUrE3H1ZZOz5RJYpf04vRWAChQKtQkOiZJuNL3reRiaW0CKYF+Jo9y9AiB252hBeZ9fpO9KgoOGPObgw8+giPiUtiUOlxqbL6I9wN4p3V07qmXP81zKPwKxGbgj/5ZJPM+MjmRuaUBcdjRyPr3YzUPkTBo0dXxo+t1XZp0SGC4Qb6aqdERfN8vW3eXRRrQopym35nmH8DFns6JZC80UsQ5C3nF18faMwzGZg16RV8VH4FyJ1EpCMHANICKb4u/QnvVpKzUfxZPYSNQ26nzmaemLHwrBJPv47DALB7dG3KEVRw4F5hZ2XgvLYZwGm1aFiMjQLFUUFxx+nvsOmhHolilQiWC5k19w1NWZuKnL5FHHkSeMuJUp/qsttB18M9mwUcCdCTttsJRB4EJYrc360wAo472n/vWfn9uP9NzN1jdxIdIQbZYZgjLEYRPzdsY+YymnkdFAkMbHEAhxCG0/tlKgDe1I7SxWzDz7HYmq3IK1BnzWUUvv+i4P8ZuC8v9X0VmwZVaZzryyG6zoQXC41zY7Mm3jijF82nPgK3fCYufCTDkpoq5HSog9bgTbsxpRQZ51BbEsVo1xNC1MOeIxL3BURRVGklcdmzAJOEPMK+q2biP1Il6qcrPS0Z/J5hzJC7MzNPnJSHG8pGOiQIN99yJK
      LOGIN: AgACopaTqOCqqjaIChsHlDe/Dk3u/bTNaxjKdj8TJ2T0+dMr3KckaMyMtG+N2f0qg+jurZIWGA6CceUr75GsiBrUew/xul8RGY67qyaBP2bry0hTV20kvexVItnU6AHvpgpl19sCQhRbglM8nYLmpiTbeVrsl3f5BwcuKbbSAox7BxQogKGoHSXJuOYmds8kynQTixgkexQmdd+wpUjmv4yzLdbYBN+RHl1s1SJa11se53V1Jgs8E2IA320/ei/8arceegxsMg4ftHy4/ook1uuyFJ6GNxd1fYaG6K8VJJ022+M6P9DB0cEKw/hal2gdHkP9R1C9n7IE5BAwntErnH8lBll/d4ETFQ1ADSf+LTi2cGJ/RmXNffVOGE71fJd07uWoquYMUbmKSS0JpXaVIikmBa6ICeija2jubQyOoL3YDHIoa9usC6aQERhhwMA0xuQjTa1OLfMc8nuSFP0pX7Io/YCIrpYrGReb039KoHYMR0AYNnT67e05UwR+ekFgEYMeX2kFK2HPOi1LjOTC0MJWkeBr3dsF0QnEr124qyvSRB/GLM0pXnTDvMFUux/47BAgFJ+0Gfh+5OBgC1gdjgcmexEDpG5jCHSgOFWQt1lcfilGBpl+nWd3BhWZsuRfdpoTwgCxKxoN1dRHuQwq6jNAnyXTGpArt3i/anpjgCrXkbI3uuUUL+4UZNzcULrxgV86dE8u
    HDFS:
      HOST: AgAx7xL5+/inzlgsNIW6wAquiiQrkoLjnCrxZyFuycmowJTb9L4w0xGXyPX4SL0FSqFEFG4/rd/7EaKH6PrCi9CbglE6VsN+uQU0jOPKVr+Ax+Vt+TMxVOBdUR4jIxRjesH4PMIoyYpAJFz70f34ydIWExXH7nfV3BIfJ45vFHiw3ci+lJBaKD+tXgCdSqjwSHgGMjxesLEyN0iXrQzQoz30EbcDIZTorwzrhsYouSommVrZGegXkG9sHvfat8Q8uMhn/+7/nEiZdPC9rZ9kNvczjpHrjuYtkw1I4t9nrLJHkrXeGjkd2Tfv2Pb0ko4kO+NC8cvK57rqc42Qpgnw3NVnZp4B5McZ1ug++5HKVrV+519lzf2UBSjuJm3xAaUeEHey6WNB99QUQjP+QPxA+3zQDQN0xfHrBGGRgtIv92HS4t3Uyry374u9argDM0uo8u1KQpiQz3NYxZuLiKoehaPAwMEwdVc4MDwihe7NCKo09W0uGzpYEIC0OpaJk2aHvEU6uYwj1DKyvPgkKdZBuGVN/b22Tul64UBjn1hkTebIKhevWBsVtXzTn6ZZTiUeFHk7X8JRz+KEff9hrROVg+UTA9kxLGqC0ucOXKVPuTRCsVdCL41Ae/B5W/iBz789/L44VDp3JOgVYnzBN5ZkrJf5tVTmC9Lry+UPEGkoDlV1ebu3rFB8hiXsL6DGf1g+/hLbS6bn1JqZ6TnbLoc=
  SUPERSET:
    GREENPLUM:
      PASSWORD: AgB8ATg5cI7D4ErIH4FRSzYFQGOV2ZUjt3Tnia0mfbju2Is1aoAfW8OuScpRZqrgdM1ABWfuu7LiC+StuOCDGzSH+gXWz5TiWQBOCJ2uIfLyorud0/6bX5SVs9JSGMOVqiyhTDL98pNk+S0Oz2FfXiLeQi/FjPSvj9wLaYnryj15PjtrZoYGSInQyvaNDclv8bFpH3Vv0ejX1KAPSxiyZ6NaWI1dh2bh7chQ7E9yjsO8L4PYtKnK4i1daDveAqfx+PkpXqc2Qip4AqfvI9JX5kwLRf6tRTL+NluEG2H5Fyu3OAVbVaLm7qLrSqUCsI2Vn93AghirgJvTmCVLQO/5oEN8YEDiyvfsFNrpKhI5Lw85hpZtYwx+QIQMmhXfGvTjW+HzuPvt6z8dfnnbm0nVag+3dKYVDVpOlkO+NXgc6R7doANkw+NAi4js5UHqpHFBe7h1BCXhn0he8LfzlSmcEa/wZZ4UKL5kEiI+xXCPaWw08I0mnNWlpYYrFK1DWnlLdb6afhOTop+3Z29IHcxyB+XSk9c6FULB3Wkyv07fjS/dOGWZx0gRWF0P/EqVOpJlAYVhSUz6RLzfA9RrGFrRB5ekEdLLhO6uivW8nDuFydvOJ+kCYeVwq5pJBBTqBI1HdNabE+LDSFeGiCbOJKEXUSbBjxiB0FhWMrGFytzrH1q+XZGA6H5yoX5zIJKYaL4zZ9h+eu3e

superset:
  enabled: true
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: true

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certManager:
  issuer:
    email: muzafarov.olymp@mail.ru

ingress:
  domain: null
  use_tls: true
  argocdServiceName: argocd-server
