deployments:
  - zone: ru-central1-a

image:
  repository: realeggsy/pyflink
  pullPolicy: IfNotPresent
  tag: 1.18
  flinkVersion: v1_18

flinkConfiguration:
  taskmanager.numberOfTaskSlots: '2'
  kubernetes.rest-service.exposed.type: ClusterIP
  kubernetes.rest-service.exposed.node-port-address-type: null
  job.autoscaler.enabled: 'true'

ingress:
  template: null
  className: null
  annotations: {}

namespace: default

defaultTaskManager:
  memory: 4g
  cpu: 2

defaultJobManager:
  memory: 2g
  cpu: 1

fullnameOverride: null

nameOverride: gdp

tolerations: []

secrets:
  FLINK:
    KAFKA:
      PASSWORD: AgAZn8QkuasWcebBLeAx5PGMdhg2UGmGYL2PmoMpEy2676+erpfYRy3lUBVDOZSApgc1jQ1sIQCavTVQEdbhn3lLGHAs2jIUttIG10/yZfTOVMSEBGRWvvcD+Il+zsGhcjrVWMq+oeqWyLv0AQhhZzw/TGuTogUQdiHm4O6VEmoz11OwQiRuvNvD/FwZFxioyebVJNSwiE2ZQrbJYTugjLmJhVBpxfA0ISVE2MFM/P5F7NPpbQNGKBJCGtAzfDaV4c6bD18mzi7jvLwHdYyKEXqIdr5RhNbZ7SUjak3cFVEKI0nBonRq3fgzlsAU1Y9xQrlloKwf8BvdgSroHXzCrqNN+9ApZR6H29dRvhMTeK3o+FjLIceRbDVlIWJk/oAe8hzhKBkA6vkc9jsXXrQjV7hwkoUO2Z2ZuUNr0SPzuRMdoT5VtG5I38au17MHrm85QAxD+dnGfe2yp6Dls6vAGrozx6LDV3Z8jv6erCZuHZjbEN1k5Llg0u8ixYgb8iAtu4QgSw3EghV0qesYI+fbuqMDYb1OMVVaeRzeUeb7E4dU8IKzS9kveOgixwgZtkKM6FAdbjZL+euiKUl5csrEkW17WUAuPV8rIsuSwbKB6xC86LCTrQkUxtY9UKD4r9WJI+cxUUbw9+TLbRiXqpiLKvC2d6tJn+8LzncvxRHYX4vU5NZn4YVBiSqubuQTrgcKyyjsveb3Hw==
    CLICKHOUSE:
      PASSWORD: AgBzzQib+L9ciGo7GBpB6bGeZ8UkTmQkihNH9i15TUsMmdxwCHw9zd+2OS7Tq2TaO3HZgKMnJzhCr1pvq+lLqzO3ZgU8sKYMtoAmIEnNqHOPmhPRjtx6vAQCbrOhIn4Ioq+o1KdnLr/n30gGN/hxTZ4ZGfGXhNrGPfjjQzliykVwAquRrYfOD47IRm/y+NjksGeAHrTVCX6k2nIDj1FQEYzeCPMnjq0SooDkfa+OT19Ce05qaQmzqjGE0WVKfqRz/BbDEPMllCGyxa2iF80BSuhbXnpsmROmm9dtZgi35JZs/+zqZK8l5jVrxxteWGqKr0MjYXD+AsUxkqAqb5yabpv7SDsZ+ryY5DdwXOkcB2CToInacWJCirh6KmHmYEQMpzRXtfUti/1/B7BDZ8pkTIP+/L8B8jKBlPVqAUdGk7hbYF8vYVLWOCutIrkUmZ+bd/cIhT0VGTVm5wT3aSBfMXlnnnMhFkKqSXAPjm8/606kb2FtjFzR4QzJKLYKq7ekd36poBuaBrVNFcyMthHKvPwU7BvIS3I6yjjSBi3P1dzjCZQNWUEPpdXWKq94vY4EYZb2XJe1oLIUAAjGUiuKvQHTk8ZK6kdUkLQCEjLaUxLLl0ysuJbcvY0GBZHLbtK1b3zWOj1+blDws6liyCdH08keIp+F/we6Oss2xludgCqd/Z04kJoO6f56msQbp/CCwk05LXc9dQ==
  SUPERSET:
    ENV:
      DB__PASSWORD: AgBbqcFPGBH+oW3cUtmeEXLm8R+25UrsjpBka/BLrUZD9TiIGKnQc52PdTkxVB293bnI/qIWFD5cvqtEvKHgiGqtFn21KISy8z2DiBz9YUlmWaQQAP/MiUBm4IPfTgZkqRZl9mnlM1ABiTbOGdKdEDxRaHIRaO6DsOlLYwre2f5DkuUmeufltCHEF1+wApXmwluTy5sZWzbSEVeUbFaB7crgbwC+qWFwG6T1K9xkRwaL4jThwQVEJK/1dGO7LcS5n5NTZBEypvBeCLMig9VMjQRguIGLR8fJ40Q9cb/IIZqH2KzuHe1clXEJdgc/3f58YG+qBB3pFN9cID+oQxNehm1MtcbZcxtSoME6MGpQI5D0D1MG7fOnlk4dcA3ueqsZozZGZt6xjBqIpqyJ83lJ0Yg2I7ANhLA9sJjc8nkj5xP3xvQatqJwB8U1Xzf3xnERW6rVIpW/nhkuix2b6kFqzBnUnwvN91uCvB/Qw8wnWNA5sWWPRlSV4ynMmwXcPsl4KfPJMtBu35cZmMlAeZRC0dud+jZ4+XWl/AjCVhZrxTks0QlO8MY+Giz+RXzjKNlmFu2CRmGGKvurfN4FP4KQMyh06x0tD41eEjSHclhBguzlLGujIrkdj1C85N/p41WTnFDDwp0Fi1z9DVJVTwjZFgy/4LN1QSxK7B5r3zSQEwTa81Ia5FpluLA4r6uLqc9Gdc+c2GmwhA==
    POSTGRES:
      PASSWORD: AgAEBlpvH9cVVz71OvL8MZihh6Vp3YuogGx0FS5FtYHT7MGy/HftNDelqjBc44NQVOTE3/ittjITpD0QDSGylOkgEMb4k/nviawCfhID1KRzFz8KnEpEapxDDJ3Nl1c+qtlGsyh1yxg4t9W4Ey2w3lek232jUM+2Tsz5n4JwFefvoFO2nD6B32ITuPFhWwfb3yUCF+iA0LD6+nDUyPnWl20Zbk+btQleYKp6ZKpBxG9UdU5IB6cYowdnXJGCSto7M/BuwmvxPvQ7cPldyHxKR1Eri6R10PkLRvOGhAhkvB0MQfxHTOguq2d+lwOLIze3fdEXC7Vb/1BNUZM1pZSqmZuwahmQkKUf9168iz1lSuuJWGwbkOj+/Xb6eqfYbjk/eJ9JsfBuWpybV93bgipi8nfwy92otr+RGMWbecl7nw1lZYxah6+z1xR5yImidY128ly4707u7zKZfKdRawSPqMpymGPfcDeJNcVOSYI+1C6JOPtssRj0SY90J41Fr1wxJsos6kVuXtVQtr1nZCJZJ6jEYcJuc89uNdqCJYlS98JqryGGd6+pkrUIVshxh4F0FEHBlL0bYS2MITZ/hRYxSfbqoK0U7fCFN6ZeLBHw1M77QJqUS9mJrCQzbQIz/hfb7bFBh4cG9MbznBpdlQpW9f2ffWVtZZmrxEgM4UBPHu9eWVezW79XL1sZhgatOSUOA6Mtmw4ZLA==
      POSTGRES__PASSWORD: AgBr1ze9B89dp0uz0y1oui34PpjVjUqlkWZG4P5lNwh792EDKZGXXjQ2o2bn+nhng4yHURCH4vW3vCJUJC0X0kkddZrm4IOUggIaC9eX2Rc6Q68ZFkkQIOUn95+wDzvIfiWEgFDuKcUF5Tj6ByzM0aznA5xEOB0AKyhCWml4KUfwzdWcNFxkJZB6LkM1BJm88t2PpDM/TdH+EQ3vfH6pZTF/WataNdanLlwVqA4f9s8tounwB97j8iyh2gAiBU1skyqzygl2VP7DIxOt5Vw1ti9KFG7eybhbvS8sbztSbQtcKsZzbza3CHBWIayN9t2aU0qiYKyLBZnk+ttBA3PC9lGNSBseVAxZkXHYe7WK9CTK/Av8EMhTKVYC1a/nx0N0Dp8JeXaAuaquCOwcuVvExrFDpN5IacI9vA2GsD66iBld4GIKrbsA0slt8GO8HHO0Glwz+i7LpXRatWUjt9ARyzdM3IsI0rXS6YheFnKD65HV+7JGjwq3oaIlscHLSIJ5Pr+lgg2+nrR2MhCJQ0kgOxagcm0cWz3k0H1ytCOAAszSm5d+jSE63TaZ2m5h1w/bJJpAZ+PIwOS26tmh9VMAxxGRUXYlbcnJcbMZgjHyfGMqA/V0F64Il4rfmpilOaAcv+zZFzt/BuKpsYq2bOZh0rT65MwIPQbSqr57FDq1dvHT+gDLqiUUT/MjpAsd8/tYpbyuGQ6M2g==

superset:
  enabled: false
  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    loadBalancerIP: null
  configOverrides:
    secret: 'SECRET_KEY = ''12345''

      '
  supersetNode:
    command:
      - /bin/sh
      - -c
      - pip install clickhouse-connect==0.7.8 && ({{ .Values.configMountPath }}/superset_bootstrap.sh
        & /usr/bin/run-server.sh)
  tolerations:
    - key: node_group
      operator: Equal
      value: superset-only
      effect: NoSchedule
  postgresql:
    auth:
      enablePostgresUser: false
    primary:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    readReplicas:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  redis:
    auth: null
    master:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
    replica:
      tolerations:
        - key: node_group
          operator: Equal
          value: superset-only
          effect: NoSchedule
  init:
    loadExamples: false

flink-kubernetes-operator:
  operatorPod:
    tolerations:
      - key: zone
        operator: Exists
        effect: NoSchedule
  webhook:
    create: true

argocd-apps:
  enabled: true
  applications:
    gdp:
      project: default
      sources:
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          targetRevision: HEAD
          path: deploy/gdp
          helm:
            valuesObject:
              argocd-apps.enabled: false
              superset.enabled: true
            valueFiles:
              - $gdp-values/deploy/gdp/values.yaml
        - repoURL: https://github.com/mm-kpfu/game-data-platform.git
          ref: gdp-values
      destination:
        name: in-cluster
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - createNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          name: gdp

certmanager:
  issuer:
    email: muzafarov.olymp@mail.ru

domain: game-data-platform.ru
